
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

using nu = NUnit.Framework;
using t = alby.pantheon.codegen.table ;

namespace alby.pantheon.codegen.test
{
	public partial class CodeGenUnitTestClass : acr.CodeGenUnitTestBase
	{
		protected void AssertObjectsAfterUpdate()
		{
			// Chain
			this.Assert٠Chain( false, obj2٠Chain, obj1٠Chain ) ; 
			 
			// Document
			this.Assert٠Document( false, obj2٠Document, obj1٠Document ) ; 
			 
			// dtproperties
			this.Assert٠dtproperties( false, obj2٠dtproperties, obj1٠dtproperties ) ; 
			 
			// Email
			this.Assert٠Email( false, obj2٠Email, obj1٠Email ) ; 
			 
			// ExpenseDetail
			this.Assert٠ExpenseDetail( false, obj2٠ExpenseDetail, obj1٠ExpenseDetail ) ; 
			 
			// FitoutDetail
			this.Assert٠FitoutDetail( false, obj2٠FitoutDetail, obj1٠FitoutDetail ) ; 
			 
			// IDGenerator
			this.Assert٠IDGenerator( false, obj2٠IDGenerator, obj1٠IDGenerator ) ; 
			 
			// LeaseComment
			this.Assert٠LeaseComment( false, obj2٠LeaseComment, obj1٠LeaseComment ) ; 
			 
			// LeaseCondition
			this.Assert٠LeaseCondition( false, obj2٠LeaseCondition, obj1٠LeaseCondition ) ; 
			 
			// LeaseType
			this.Assert٠LeaseType( false, obj2٠LeaseType, obj1٠LeaseType ) ; 
			 
			// Party
			this.Assert٠Party( false, obj2٠Party, obj1٠Party ) ; 
			 
			// PaymentType
			this.Assert٠PaymentType( false, obj2٠PaymentType, obj1٠PaymentType ) ; 
			 
			// Precinct
			this.Assert٠Precinct( false, obj2٠Precinct, obj1٠Precinct ) ; 
			 
			// RDMFeeParam
			this.Assert٠RDMFeeParam( false, obj2٠RDMFeeParam, obj1٠RDMFeeParam ) ; 
			 
			// RentReviewType
			this.Assert٠RentReviewType( false, obj2٠RentReviewType, obj1٠RentReviewType ) ; 
			 
			// SalesCategory
			this.Assert٠SalesCategory( false, obj2٠SalesCategory, obj1٠SalesCategory ) ; 
			 
			// Sector
			this.Assert٠Sector( false, obj2٠Sector, obj1٠Sector ) ; 
			 
			// ShopType
			this.Assert٠ShopType( false, obj2٠ShopType, obj1٠ShopType ) ; 
			 
			// SolicitorWebService
			this.Assert٠SolicitorWebService( false, obj2٠SolicitorWebService, obj1٠SolicitorWebService ) ; 
			 
			// SurrenderDetail
			this.Assert٠SurrenderDetail( false, obj2٠SurrenderDetail, obj1٠SurrenderDetail ) ; 
			 
			// VacantPossessionDetail
			this.Assert٠VacantPossessionDetail( false, obj2٠VacantPossessionDetail, obj1٠VacantPossessionDetail ) ; 
			 
			// Address
			this.Assert٠Address( false, obj2٠Address, obj1٠Address ) ; 
			 
			// Centre
			this.Assert٠Centre( false, obj2٠Centre, obj1٠Centre ) ; 
			 
			// Communication
			this.Assert٠Communication( false, obj2٠Communication, obj1٠Communication ) ; 
			 
			// CostCentreStage
			this.Assert٠CostCentreStage( false, obj2٠CostCentreStage, obj1٠CostCentreStage ) ; 
			 
			// CostCentreOutgoing
			this.Assert٠CostCentreOutgoing( false, obj2٠CostCentreOutgoing, obj1٠CostCentreOutgoing ) ; 
			 
			// CostCentreOutgoingArchive
			this.Assert٠CostCentreOutgoingArchive( false, obj2٠CostCentreOutgoingArchive, obj1٠CostCentreOutgoingArchive ) ; 
			 
			// Franchise
			this.Assert٠Franchise( false, obj2٠Franchise, obj1٠Franchise ) ; 
			 
			// LeaseExecutive
			this.Assert٠LeaseExecutive( false, obj2٠LeaseExecutive, obj1٠LeaseExecutive ) ; 
			 
			// Lessee
			this.Assert٠Lessee( false, obj2٠Lessee, obj1٠Lessee ) ; 
			 
			// RentReview
			this.Assert٠RentReview( false, obj2٠RentReview, obj1٠RentReview ) ; 
			 
			// ConsumerPriceIndexRentReview
			this.Assert٠ConsumerPriceIndexRentReview( false, obj2٠ConsumerPriceIndexRentReview, obj1٠ConsumerPriceIndexRentReview ) ; 
			 
			// FixedIncreaseRentReview
			this.Assert٠FixedIncreaseRentReview( false, obj2٠FixedIncreaseRentReview, obj1٠FixedIncreaseRentReview ) ; 
			 
			// RentDetail
			this.Assert٠RentDetail( false, obj2٠RentDetail, obj1٠RentDetail ) ; 
			 
			// Solicitor
			this.Assert٠Solicitor( false, obj2٠Solicitor, obj1٠Solicitor ) ; 
			 
			// Staff
			this.Assert٠Staff( false, obj2٠Staff, obj1٠Staff ) ; 
			 
			// LeaseAdministration
			this.Assert٠LeaseAdministration( false, obj2٠LeaseAdministration, obj1٠LeaseAdministration ) ; 
			 
			// Lease
			this.Assert٠Lease( false, obj2٠Lease, obj1٠Lease ) ; 
			 
			// LeaseGuarantor
			this.Assert٠LeaseGuarantor( false, obj2٠LeaseGuarantor, obj1٠LeaseGuarantor ) ; 
			 
			// LogEntry
			this.Assert٠LogEntry( false, obj2٠LogEntry, obj1٠LogEntry ) ; 
			 
		}
	}

}

