
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

using nu = NUnit.Framework;
using t = alby.pantheon.codegen.table ;

namespace alby.pantheon.codegen.test
{
	public partial class CodeGenUnitTestClass : acr.CodeGenUnitTestBase
	{
		protected void PopulateOverride٠SolicitorWebService( bool insert, t.SolicitorWebService obj )
		{
			if ( insert )
			{
				// obj.SolicitorWebServiceGUID = null ;
				// obj.Name = null ;
				// obj.DevUrl = null ;
				// obj.IntgUrl = null ;
				// obj.TestUrl = null ;
				// obj.StagUrl = null ;
				// obj.ProdUrl = null ;
				// obj.DRUrl = null ;
				// obj.DevCertFilename = null ;
				// obj.IntgCertFilename = null ;
				// obj.TestCertFilename = null ;
				// obj.StagCertFilename = null ;
				// obj.ProdCertFilename = null ;
				// obj.DRCertFilename = null ;
				// obj.UpdateUserCode = null ;
				// obj.UpdateDateTime = null ;
			}
			else // update
			{
				// obj.SolicitorWebServiceGUID = null ;
				// obj.Name = null ;
				// obj.DevUrl = null ;
				// obj.IntgUrl = null ;
				// obj.TestUrl = null ;
				// obj.StagUrl = null ;
				// obj.ProdUrl = null ;
				// obj.DRUrl = null ;
				// obj.DevCertFilename = null ;
				// obj.IntgCertFilename = null ;
				// obj.TestCertFilename = null ;
				// obj.StagCertFilename = null ;
				// obj.ProdCertFilename = null ;
				// obj.DRCertFilename = null ;
				// obj.UpdateUserCode = null ;
				// obj.UpdateDateTime = null ;
			}
			 
		}
	}

}

