
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

using nu = NUnit.Framework;
using t = alby.pantheon.codegen.table ;

namespace alby.pantheon.codegen.test
{
	public partial class CodeGenUnitTestClass : acr.CodeGenUnitTestBase
	{
		protected void AssertObjectsNew()
		{
			// Chain
			this.AssertFlagsObjectNew( obj0٠Chain ) ; 
			 
			// Document
			this.AssertFlagsObjectNew( obj0٠Document ) ; 
			 
			// dtproperties
			this.AssertFlagsObjectNew( obj0٠dtproperties ) ; 
			 
			// Email
			this.AssertFlagsObjectNew( obj0٠Email ) ; 
			 
			// ExpenseDetail
			this.AssertFlagsObjectNew( obj0٠ExpenseDetail ) ; 
			 
			// FitoutDetail
			this.AssertFlagsObjectNew( obj0٠FitoutDetail ) ; 
			 
			// IDGenerator
			this.AssertFlagsObjectNew( obj0٠IDGenerator ) ; 
			 
			// LeaseComment
			this.AssertFlagsObjectNew( obj0٠LeaseComment ) ; 
			 
			// LeaseCondition
			this.AssertFlagsObjectNew( obj0٠LeaseCondition ) ; 
			 
			// LeaseType
			this.AssertFlagsObjectNew( obj0٠LeaseType ) ; 
			 
			// Party
			this.AssertFlagsObjectNew( obj0٠Party ) ; 
			 
			// PaymentType
			this.AssertFlagsObjectNew( obj0٠PaymentType ) ; 
			 
			// Precinct
			this.AssertFlagsObjectNew( obj0٠Precinct ) ; 
			 
			// RDMFeeParam
			this.AssertFlagsObjectNew( obj0٠RDMFeeParam ) ; 
			 
			// RentReviewType
			this.AssertFlagsObjectNew( obj0٠RentReviewType ) ; 
			 
			// SalesCategory
			this.AssertFlagsObjectNew( obj0٠SalesCategory ) ; 
			 
			// Sector
			this.AssertFlagsObjectNew( obj0٠Sector ) ; 
			 
			// ShopType
			this.AssertFlagsObjectNew( obj0٠ShopType ) ; 
			 
			// SolicitorWebService
			this.AssertFlagsObjectNew( obj0٠SolicitorWebService ) ; 
			 
			// SurrenderDetail
			this.AssertFlagsObjectNew( obj0٠SurrenderDetail ) ; 
			 
			// VacantPossessionDetail
			this.AssertFlagsObjectNew( obj0٠VacantPossessionDetail ) ; 
			 
			// Address
			this.AssertFlagsObjectNew( obj0٠Address ) ; 
			 
			// Centre
			this.AssertFlagsObjectNew( obj0٠Centre ) ; 
			 
			// Communication
			this.AssertFlagsObjectNew( obj0٠Communication ) ; 
			 
			// CostCentreStage
			this.AssertFlagsObjectNew( obj0٠CostCentreStage ) ; 
			 
			// CostCentreOutgoing
			this.AssertFlagsObjectNew( obj0٠CostCentreOutgoing ) ; 
			 
			// CostCentreOutgoingArchive
			this.AssertFlagsObjectNew( obj0٠CostCentreOutgoingArchive ) ; 
			 
			// Franchise
			this.AssertFlagsObjectNew( obj0٠Franchise ) ; 
			 
			// LeaseExecutive
			this.AssertFlagsObjectNew( obj0٠LeaseExecutive ) ; 
			 
			// Lessee
			this.AssertFlagsObjectNew( obj0٠Lessee ) ; 
			 
			// RentReview
			this.AssertFlagsObjectNew( obj0٠RentReview ) ; 
			 
			// ConsumerPriceIndexRentReview
			this.AssertFlagsObjectNew( obj0٠ConsumerPriceIndexRentReview ) ; 
			 
			// FixedIncreaseRentReview
			this.AssertFlagsObjectNew( obj0٠FixedIncreaseRentReview ) ; 
			 
			// RentDetail
			this.AssertFlagsObjectNew( obj0٠RentDetail ) ; 
			 
			// Solicitor
			this.AssertFlagsObjectNew( obj0٠Solicitor ) ; 
			 
			// Staff
			this.AssertFlagsObjectNew( obj0٠Staff ) ; 
			 
			// LeaseAdministration
			this.AssertFlagsObjectNew( obj0٠LeaseAdministration ) ; 
			 
			// Lease
			this.AssertFlagsObjectNew( obj0٠Lease ) ; 
			 
			// LeaseGuarantor
			this.AssertFlagsObjectNew( obj0٠LeaseGuarantor ) ; 
			 
			// LogEntry
			this.AssertFlagsObjectNew( obj0٠LogEntry ) ; 
			 
		}
	}

}

