
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

using nu = NUnit.Framework;
using t = alby.pantheon.codegen.table ;

namespace alby.pantheon.codegen.test
{
	public partial class CodeGenUnitTestClass : acr.CodeGenUnitTestBase
	{
		protected void Populate٠SurrenderDetail( bool insert, t.SurrenderDetail obj )
		{
			if ( insert )
			{
				obj.SurrenderDetailID = toint( factory٠SurrenderDetailFactory.GetNextIdˡ( _connection, t.SurrenderDetail.column٠SurrenderDetailID, true ).ToString() ) ;
				obj.TenantSolicitorName = "@" ;
				obj.TenantName = "@" ;
				obj.TenantShopNo = "@" ;
				obj.TenantSurrenderApplicable = "@" ;
				obj.TenantSurrenderDate = new DateTime(1900,1,1) ;
				obj.TenantSurrenderSumPayableByLessee = -1.0m ;
				obj.TenantSurrenderSumPayableByLessor = -1.0m ;
				obj.TenantMakeGoodRequiredIndicator = "@" ;
				obj.TenantLeaseNumber = "@" ;
				obj.TenantLeaseDate = new DateTime(1900,1,1) ;
				obj.TenantSendDocsTo = "@" ;
				obj.LesseeSolicitorName = "@" ;
				obj.LesseeName = "@" ;
				obj.LesseeShopNo = "@" ;
				obj.LesseeSurrenderApplicable = "@" ;
				obj.LesseeSurrenderDate = new DateTime(1900,1,1) ;
				obj.LesseeSurrenderSumPayableByLessee = -1.0m ;
				obj.LesseeSurrenderSumPayableByLessor = -1.0m ;
				obj.LesseeMakeGoodRequiredIndicator = "@" ;
				obj.LesseeLeaseNumber = "@" ;
				obj.LesseeLeaseDate = new DateTime(1900,1,1) ;
				obj.LesseeSendDocsTo = "@" ;
				obj.UpdateUserCode = "@" ;
				obj.UpdateDateTime = new DateTime(1900,1,1) ;
				obj.TenantTradingName = "@" ;
				obj.LesseeTradingName = "@" ;
				obj.LesseeLiableLegalFeesIndicator = "@" ;
			}
			else // update
			{
				obj.TenantSolicitorName = "#" ;
				obj.TenantName = "#" ;
				obj.TenantShopNo = "#" ;
				obj.TenantSurrenderApplicable = "#" ;
				obj.TenantSurrenderDate = new DateTime(1901,12,31) ;
				obj.TenantSurrenderSumPayableByLessee = -2.0m ;
				obj.TenantSurrenderSumPayableByLessor = -2.0m ;
				obj.TenantMakeGoodRequiredIndicator = "#" ;
				obj.TenantLeaseNumber = "#" ;
				obj.TenantLeaseDate = new DateTime(1901,12,31) ;
				obj.TenantSendDocsTo = "#" ;
				obj.LesseeSolicitorName = "#" ;
				obj.LesseeName = "#" ;
				obj.LesseeShopNo = "#" ;
				obj.LesseeSurrenderApplicable = "#" ;
				obj.LesseeSurrenderDate = new DateTime(1901,12,31) ;
				obj.LesseeSurrenderSumPayableByLessee = -2.0m ;
				obj.LesseeSurrenderSumPayableByLessor = -2.0m ;
				obj.LesseeMakeGoodRequiredIndicator = "#" ;
				obj.LesseeLeaseNumber = "#" ;
				obj.LesseeLeaseDate = new DateTime(1901,12,31) ;
				obj.LesseeSendDocsTo = "#" ;
				obj.UpdateUserCode = "#" ;
				obj.UpdateDateTime = new DateTime(1901,12,31) ;
				obj.TenantTradingName = "#" ;
				obj.LesseeTradingName = "#" ;
				obj.LesseeLiableLegalFeesIndicator = "#" ;
			}
			 
		}
	}

}

