
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

using nu = NUnit.Framework;
using t = alby.pantheon.codegen.table ;

namespace alby.pantheon.codegen.test
{
	public partial class CodeGenUnitTestClass : acr.CodeGenUnitTestBase
	{
		protected void PopulateOverride٠Lease( bool insert, t.Lease obj )
		{
			if ( insert )
			{
				// obj.LeaseID = null ;
				// obj.LeaseStatus = null ;
				// obj.PIMSUsageCode = null ;
				// obj.LeaseTypeID = null ;
				// obj.CostCentreStageID = null ;
				// obj.StageNumber = null ;
				// obj.ShopNo = null ;
				// obj.Level = null ;
				// obj.Area = null ;
				// obj.AreaType = null ;
				// obj.PrecinctID = null ;
				// obj.SectorID = null ;
				// obj.ShopTypeID = null ;
				// obj.LeaseExecutiveID = null ;
				// obj.LeaseGuarantorID = null ;
				// obj.LesseeID = null ;
				// obj.SolicitorID = null ;
				// obj.CommenceDate = null ;
				// obj.ExpiryDate = null ;
				// obj.LeaseTermYears = null ;
				// obj.LeaseTermMonths = null ;
				// obj.LeaseTermDays = null ;
				// obj.LeaseTermText = null ;
				// obj.LOIIssueDate = null ;
				// obj.LOIDueDate = null ;
				// obj.CompanyName = null ;
				// obj.ACN = null ;
				// obj.ABN = null ;
				// obj.LesseeName = null ;
				// obj.TradingName = null ;
				// obj.ChainID = null ;
				// obj.SalesCategoryID = null ;
				// obj.PermittedUse = null ;
				// obj.ExpenseDetailID = null ;
				// obj.FitoutDetailID = null ;
				// obj.LeaseAdministrationID = null ;
				// obj.LeaseCommentID = null ;
				// obj.LeaseConditionID = null ;
				// obj.RentDetailID = null ;
				// obj.SurrenderDetailID = null ;
				// obj.VacantPossessionDetailID = null ;
				// obj.UpdateUserCode = null ;
				// obj.UpdateDateTime = null ;
			}
			else // update
			{
				// obj.LeaseID = null ;
				// obj.LeaseStatus = null ;
				// obj.PIMSUsageCode = null ;
				// obj.LeaseTypeID = null ;
				// obj.CostCentreStageID = null ;
				// obj.StageNumber = null ;
				// obj.ShopNo = null ;
				// obj.Level = null ;
				// obj.Area = null ;
				// obj.AreaType = null ;
				// obj.PrecinctID = null ;
				// obj.SectorID = null ;
				// obj.ShopTypeID = null ;
				// obj.LeaseExecutiveID = null ;
				// obj.LeaseGuarantorID = null ;
				// obj.LesseeID = null ;
				// obj.SolicitorID = null ;
				// obj.CommenceDate = null ;
				// obj.ExpiryDate = null ;
				// obj.LeaseTermYears = null ;
				// obj.LeaseTermMonths = null ;
				// obj.LeaseTermDays = null ;
				// obj.LeaseTermText = null ;
				// obj.LOIIssueDate = null ;
				// obj.LOIDueDate = null ;
				// obj.CompanyName = null ;
				// obj.ACN = null ;
				// obj.ABN = null ;
				// obj.LesseeName = null ;
				// obj.TradingName = null ;
				// obj.ChainID = null ;
				// obj.SalesCategoryID = null ;
				// obj.PermittedUse = null ;
				// obj.ExpenseDetailID = null ;
				// obj.FitoutDetailID = null ;
				// obj.LeaseAdministrationID = null ;
				// obj.LeaseCommentID = null ;
				// obj.LeaseConditionID = null ;
				// obj.RentDetailID = null ;
				// obj.SurrenderDetailID = null ;
				// obj.VacantPossessionDetailID = null ;
				// obj.UpdateUserCode = null ;
				// obj.UpdateDateTime = null ;
			}
			 
		}
	}

}

