
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

using nu = NUnit.Framework;
using t = alby.pantheon.codegen.table ;

namespace alby.pantheon.codegen.test
{
	public partial class CodeGenUnitTestClass : acr.CodeGenUnitTestBase
	{
		protected void Assert٠LeaseGuarantor( bool insert, t.LeaseGuarantor newobj, t.LeaseGuarantor oldobj )
		{
			acr.CodeGenEtc.ConsoleMessage( ! this.QuietMode, "[39/40] LeaseGuarantor - assert" ) ;
		 
			nu.Assert.IsNotNull( newobj.PartyID, "LeaseGuarantor.PartyID" ) ;
			nu.Assert.IsNotNull( newobj.LeaseID, "LeaseGuarantor.LeaseID" ) ;
			nu.Assert.IsNotNull( newobj.ACN, "LeaseGuarantor.ACN" ) ;
			nu.Assert.IsNotNull( newobj.DisplayOrder, "LeaseGuarantor.DisplayOrder" ) ;
			nu.Assert.IsNotNull( newobj.UpdateUserCode, "LeaseGuarantor.UpdateUserCode" ) ;
			nu.Assert.IsNotNull( newobj.UpdateDateTime, "LeaseGuarantor.UpdateDateTime" ) ;
			nu.Assert.IsNotNull( newobj.RowTimestamp, "LeaseGuarantor.RowTimestamp" ) ;
		 
			base.AssertAreEqual( newobj.PartyID, oldobj.PartyID, "LeaseGuarantor.PartyID" ) ;
			base.AssertAreEqual( newobj.LeaseID, oldobj.LeaseID, "LeaseGuarantor.LeaseID" ) ;
			base.AssertAreEqual( newobj.ACN, oldobj.ACN, "LeaseGuarantor.ACN" ) ;
			base.AssertAreEqual( newobj.DisplayOrder, oldobj.DisplayOrder, "LeaseGuarantor.DisplayOrder" ) ;
			base.AssertAreEqual( newobj.UpdateUserCode, oldobj.UpdateUserCode, "LeaseGuarantor.UpdateUserCode" ) ;
			base.AssertAreEqual( newobj.UpdateDateTime, oldobj.UpdateDateTime, "LeaseGuarantor.UpdateDateTime" ) ;
		 
		}
	}

}

