
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

using nu = NUnit.Framework;
using t = alby.pantheon.codegen.table ;

namespace alby.pantheon.codegen.test
{
	public partial class CodeGenUnitTestClass : acr.CodeGenUnitTestBase
	{
		protected void Assert٠Lessee( bool insert, t.Lessee newobj, t.Lessee oldobj )
		{
			acr.CodeGenEtc.ConsoleMessage( ! this.QuietMode, "[30/40] Lessee - assert" ) ;
		 
			nu.Assert.IsNotNull( newobj.PartyID, "Lessee.PartyID" ) ;
			nu.Assert.IsNotNull( newobj.JobTitle, "Lessee.JobTitle" ) ;
			nu.Assert.IsNotNull( newobj.UpdateUserCode, "Lessee.UpdateUserCode" ) ;
			nu.Assert.IsNotNull( newobj.UpdateDateTime, "Lessee.UpdateDateTime" ) ;
			nu.Assert.IsNotNull( newobj.RowTimestamp, "Lessee.RowTimestamp" ) ;
		 
			base.AssertAreEqual( newobj.PartyID, oldobj.PartyID, "Lessee.PartyID" ) ;
			base.AssertAreEqual( newobj.JobTitle, oldobj.JobTitle, "Lessee.JobTitle" ) ;
			base.AssertAreEqual( newobj.UpdateUserCode, oldobj.UpdateUserCode, "Lessee.UpdateUserCode" ) ;
			base.AssertAreEqual( newobj.UpdateDateTime, oldobj.UpdateDateTime, "Lessee.UpdateDateTime" ) ;
		 
		}
	}

}

