
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

using nu = NUnit.Framework;
using t = alby.pantheon.codegen.table ;

namespace alby.pantheon.codegen.test
{
	public partial class CodeGenUnitTestClass : acr.CodeGenUnitTestBase
	{
		protected void Populate٠LeaseComment( bool insert, t.LeaseComment obj )
		{
			if ( insert )
			{
				obj.LeaseCommentID = toint( factory٠LeaseCommentFactory.GetNextIdˡ( _connection, t.LeaseComment.column٠LeaseCommentID, true ).ToString() ) ;
				obj.GeneralComment = "@" ;
				obj.UpdateUserCode = "@" ;
				obj.UpdateDateTime = new DateTime(1900,1,1) ;
			}
			else // update
			{
				obj.GeneralComment = "#" ;
				obj.UpdateUserCode = "#" ;
				obj.UpdateDateTime = new DateTime(1901,12,31) ;
			}
			 
		}
	}

}

