
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

using nu = NUnit.Framework;
using t = alby.pantheon.codegen.table ;

namespace alby.pantheon.codegen.test
{
	public partial class CodeGenUnitTestClass : acr.CodeGenUnitTestBase
	{
		protected void PopulateOverride٠RentDetail( bool insert, t.RentDetail obj )
		{
			if ( insert )
			{
				// obj.RentDetailID = null ;
				// obj.BaseRent = null ;
				// obj.BaseRentSQM = null ;
				// obj.BudgetedBaseRent = null ;
				// obj.CurrentBaseRent = null ;
				// obj.PercentageRent = null ;
				// obj.PercentageRentText = null ;
				// obj.MarketingLevy = null ;
				// obj.SpecialOpeningPromotionLevy = null ;
				// obj.MonthlyRent = null ;
				// obj.RentPaymentCommencementDate = null ;
				// obj.RentPaymentCommencementDateText = null ;
				// obj.MarketingLevyPaymentCommencementDate = null ;
				// obj.MarketingLevyPaymentCommencementDateText = null ;
				// obj.RentReviewID = null ;
				// obj.RentFreePeriod = null ;
				// obj.DirectorsPersonalGuaranteeIndicator = null ;
				// obj.BaseRentPayableIndicator = null ;
				// obj.OutgoingsPayableIndicator = null ;
				// obj.MarketingLevyPayableIndicator = null ;
				// obj.BankGuaranteeRequiredIndicator = null ;
				// obj.BankGuaranteeAmount = null ;
				// obj.BankGuaranteeAmountCalculated = null ;
				// obj.ReducedBankGuaranteeAmount = null ;
				// obj.BankGuaranteeRequiredLesseeIndicator = null ;
				// obj.ActualBankGuaranteeAmount = null ;
				// obj.OptionRequiredIndicator = null ;
				// obj.OptionTermYears = null ;
				// obj.OptionTermMonths = null ;
				// obj.OptionTermDays = null ;
				// obj.OptionTermText = null ;
				// obj.AtOptionRentReviewTypeID = null ;
				// obj.DuringOptionRentReviewTypeID = null ;
				// obj.UpdateUserCode = null ;
				// obj.UpdateDateTime = null ;
				// obj.ConsumerPriceIndexDescriptionAtOption = null ;
				// obj.ConsumerPriceIndexDescriptionDuringOption = null ;
				// obj.RentReviewIncreaseAtOption = null ;
				// obj.RentReviewIncreaseDuringOption = null ;
			}
			else // update
			{
				// obj.RentDetailID = null ;
				// obj.BaseRent = null ;
				// obj.BaseRentSQM = null ;
				// obj.BudgetedBaseRent = null ;
				// obj.CurrentBaseRent = null ;
				// obj.PercentageRent = null ;
				// obj.PercentageRentText = null ;
				// obj.MarketingLevy = null ;
				// obj.SpecialOpeningPromotionLevy = null ;
				// obj.MonthlyRent = null ;
				// obj.RentPaymentCommencementDate = null ;
				// obj.RentPaymentCommencementDateText = null ;
				// obj.MarketingLevyPaymentCommencementDate = null ;
				// obj.MarketingLevyPaymentCommencementDateText = null ;
				// obj.RentReviewID = null ;
				// obj.RentFreePeriod = null ;
				// obj.DirectorsPersonalGuaranteeIndicator = null ;
				// obj.BaseRentPayableIndicator = null ;
				// obj.OutgoingsPayableIndicator = null ;
				// obj.MarketingLevyPayableIndicator = null ;
				// obj.BankGuaranteeRequiredIndicator = null ;
				// obj.BankGuaranteeAmount = null ;
				// obj.BankGuaranteeAmountCalculated = null ;
				// obj.ReducedBankGuaranteeAmount = null ;
				// obj.BankGuaranteeRequiredLesseeIndicator = null ;
				// obj.ActualBankGuaranteeAmount = null ;
				// obj.OptionRequiredIndicator = null ;
				// obj.OptionTermYears = null ;
				// obj.OptionTermMonths = null ;
				// obj.OptionTermDays = null ;
				// obj.OptionTermText = null ;
				// obj.AtOptionRentReviewTypeID = null ;
				// obj.DuringOptionRentReviewTypeID = null ;
				// obj.UpdateUserCode = null ;
				// obj.UpdateDateTime = null ;
				// obj.ConsumerPriceIndexDescriptionAtOption = null ;
				// obj.ConsumerPriceIndexDescriptionDuringOption = null ;
				// obj.RentReviewIncreaseAtOption = null ;
				// obj.RentReviewIncreaseDuringOption = null ;
			}
			 
		}
	}

}

