
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

using nu = NUnit.Framework;
using t = alby.pantheon.codegen.table ;

namespace alby.pantheon.codegen.test
{
	public partial class CodeGenUnitTestClass : acr.CodeGenUnitTestBase
	{
		protected void Assert٠dtproperties( bool insert, t.dtproperties newobj, t.dtproperties oldobj )
		{
			acr.CodeGenEtc.ConsoleMessage( ! this.QuietMode, "[3/40] dtproperties - assert" ) ;
		 
			nu.Assert.IsNotNull( newobj.id, "dtproperties.id" ) ;
			nu.Assert.IsNotNull( newobj.objectid, "dtproperties.objectid" ) ;
			nu.Assert.IsNotNull( newobj.property, "dtproperties.property" ) ;
			nu.Assert.IsNotNull( newobj.value, "dtproperties.value" ) ;
			nu.Assert.IsNotNull( newobj.uvalue, "dtproperties.uvalue" ) ;
			nu.Assert.IsNotNull( newobj.lvalue, "dtproperties.lvalue" ) ;
			nu.Assert.IsNotNull( newobj.version, "dtproperties.version" ) ;
		 
			base.AssertAreEqual( newobj.objectid, oldobj.objectid, "dtproperties.objectid" ) ;
			base.AssertAreEqual( newobj.property, oldobj.property, "dtproperties.property" ) ;
			base.AssertAreEqual( newobj.value, oldobj.value, "dtproperties.value" ) ;
			base.AssertAreEqual( newobj.uvalue, oldobj.uvalue, "dtproperties.uvalue" ) ;
			base.AssertAreEqual( newobj.lvalue, oldobj.lvalue, "dtproperties.lvalue" ) ;
			base.AssertAreEqual( newobj.version, oldobj.version, "dtproperties.version" ) ;
		 
		}
	}

}

