
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

using nu = NUnit.Framework;
using t = alby.pantheon.codegen.table ;

namespace alby.pantheon.codegen.test
{
	public partial class CodeGenUnitTestClass : acr.CodeGenUnitTestBase
	{
		protected void Populate٠Document( bool insert, t.Document obj )
		{
			if ( insert )
			{
				obj.DocumentID = toint( factory٠DocumentFactory.GetNextIdˡ( _connection, t.Document.column٠DocumentID, true ).ToString() ) ;
				obj.LeaseID = -100 ;
				obj.Description = "@" ;
				obj.Type = "@" ;
				obj.BinaryData = new byte[] { 0x01 } ;
				obj.UpdateUserCode = "@" ;
				obj.UpdateDateTime = new DateTime(1900,1,1) ;
			}
			else // update
			{
				obj.LeaseID = -200 ;
				obj.Description = "#" ;
				obj.Type = "#" ;
				obj.BinaryData = new byte[] { 0x02 } ;
				obj.UpdateUserCode = "#" ;
				obj.UpdateDateTime = new DateTime(1901,12,31) ;
			}
			 
		}
	}

}

