
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

using nu = NUnit.Framework;
using t = alby.pantheon.codegen.table ;

namespace alby.pantheon.codegen.test
{
	public partial class CodeGenUnitTestClass : acr.CodeGenUnitTestBase
	{
		protected void PopulateOverride٠SurrenderDetail( bool insert, t.SurrenderDetail obj )
		{
			if ( insert )
			{
				// obj.SurrenderDetailID = null ;
				// obj.TenantSolicitorName = null ;
				// obj.TenantName = null ;
				// obj.TenantShopNo = null ;
				// obj.TenantSurrenderApplicable = null ;
				// obj.TenantSurrenderDate = null ;
				// obj.TenantSurrenderSumPayableByLessee = null ;
				// obj.TenantSurrenderSumPayableByLessor = null ;
				// obj.TenantMakeGoodRequiredIndicator = null ;
				// obj.TenantLeaseNumber = null ;
				// obj.TenantLeaseDate = null ;
				// obj.TenantSendDocsTo = null ;
				// obj.LesseeSolicitorName = null ;
				// obj.LesseeName = null ;
				// obj.LesseeShopNo = null ;
				// obj.LesseeSurrenderApplicable = null ;
				// obj.LesseeSurrenderDate = null ;
				// obj.LesseeSurrenderSumPayableByLessee = null ;
				// obj.LesseeSurrenderSumPayableByLessor = null ;
				// obj.LesseeMakeGoodRequiredIndicator = null ;
				// obj.LesseeLeaseNumber = null ;
				// obj.LesseeLeaseDate = null ;
				// obj.LesseeSendDocsTo = null ;
				// obj.UpdateUserCode = null ;
				// obj.UpdateDateTime = null ;
				// obj.TenantTradingName = null ;
				// obj.LesseeTradingName = null ;
				// obj.LesseeLiableLegalFeesIndicator = null ;
			}
			else // update
			{
				// obj.SurrenderDetailID = null ;
				// obj.TenantSolicitorName = null ;
				// obj.TenantName = null ;
				// obj.TenantShopNo = null ;
				// obj.TenantSurrenderApplicable = null ;
				// obj.TenantSurrenderDate = null ;
				// obj.TenantSurrenderSumPayableByLessee = null ;
				// obj.TenantSurrenderSumPayableByLessor = null ;
				// obj.TenantMakeGoodRequiredIndicator = null ;
				// obj.TenantLeaseNumber = null ;
				// obj.TenantLeaseDate = null ;
				// obj.TenantSendDocsTo = null ;
				// obj.LesseeSolicitorName = null ;
				// obj.LesseeName = null ;
				// obj.LesseeShopNo = null ;
				// obj.LesseeSurrenderApplicable = null ;
				// obj.LesseeSurrenderDate = null ;
				// obj.LesseeSurrenderSumPayableByLessee = null ;
				// obj.LesseeSurrenderSumPayableByLessor = null ;
				// obj.LesseeMakeGoodRequiredIndicator = null ;
				// obj.LesseeLeaseNumber = null ;
				// obj.LesseeLeaseDate = null ;
				// obj.LesseeSendDocsTo = null ;
				// obj.UpdateUserCode = null ;
				// obj.UpdateDateTime = null ;
				// obj.TenantTradingName = null ;
				// obj.LesseeTradingName = null ;
				// obj.LesseeLiableLegalFeesIndicator = null ;
			}
			 
		}
	}

}

