
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

using nu = NUnit.Framework;
using t = alby.pantheon.codegen.table ;

namespace alby.pantheon.codegen.test
{
	public partial class CodeGenUnitTestClass : acr.CodeGenUnitTestBase
	{
		protected void PopulateOverride٠RentReviewType( bool insert, t.RentReviewType obj )
		{
			if ( insert )
			{
				// obj.RentReviewTypeID = null ;
				// obj.RentReviewTypeDescription = null ;
				// obj.UpdateUserCode = null ;
				// obj.UpdateDateTime = null ;
			}
			else // update
			{
				// obj.RentReviewTypeID = null ;
				// obj.RentReviewTypeDescription = null ;
				// obj.UpdateUserCode = null ;
				// obj.UpdateDateTime = null ;
			}
			 
		}
	}

}

