
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

using nu = NUnit.Framework;
using t = alby.pantheon.codegen.table ;

namespace alby.pantheon.codegen.test
{
	public partial class CodeGenUnitTestClass : acr.CodeGenUnitTestBase
	{
		protected void Populate٠CostCentreStage( bool insert, t.CostCentreStage obj )
		{
			if ( insert )
			{
				obj.CostCentreStageID = toint( factory٠CostCentreStageFactory.GetNextIdˡ( _connection, t.CostCentreStage.column٠CostCentreStageID, true ).ToString() ) ;
				obj.CentreID = obj1٠Centre != null ? obj1٠Centre.PartyID : obj0٠Centre.PartyID ;
				obj.CostCentreCode = "@" ;
				obj.CostCentreDescription = "@" ;
				obj.UpdateUserCode = "@" ;
				obj.UpdateDateTime = new DateTime(1900,1,1) ;
				obj.DeletionIndicator = "@" ;
			}
			else // update
			{
				obj.CostCentreCode = "#" ;
				obj.CostCentreDescription = "#" ;
				obj.UpdateUserCode = "#" ;
				obj.UpdateDateTime = new DateTime(1901,12,31) ;
				obj.DeletionIndicator = "#" ;
			}
			 
		}
	}

}

