
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

using nu = NUnit.Framework;
using t = alby.pantheon.codegen.table ;

namespace alby.pantheon.codegen.test
{
	public partial class CodeGenUnitTestClass : acr.CodeGenUnitTestBase
	{
		protected void Assert٠Sector( bool insert, t.Sector newobj, t.Sector oldobj )
		{
			acr.CodeGenEtc.ConsoleMessage( ! this.QuietMode, "[17/40] Sector - assert" ) ;
		 
			nu.Assert.IsNotNull( newobj.SectorID, "Sector.SectorID" ) ;
			nu.Assert.IsNotNull( newobj.SectorDescription, "Sector.SectorDescription" ) ;
			nu.Assert.IsNotNull( newobj.UpdateUserCode, "Sector.UpdateUserCode" ) ;
			nu.Assert.IsNotNull( newobj.UpdateDateTime, "Sector.UpdateDateTime" ) ;
			nu.Assert.IsNotNull( newobj.RowTimestamp, "Sector.RowTimestamp" ) ;
			nu.Assert.IsNotNull( newobj.DeletionIndicator, "Sector.DeletionIndicator" ) ;
		 
			base.AssertAreEqual( newobj.SectorID, oldobj.SectorID, "Sector.SectorID" ) ;
			base.AssertAreEqual( newobj.SectorDescription, oldobj.SectorDescription, "Sector.SectorDescription" ) ;
			base.AssertAreEqual( newobj.UpdateUserCode, oldobj.UpdateUserCode, "Sector.UpdateUserCode" ) ;
			base.AssertAreEqual( newobj.UpdateDateTime, oldobj.UpdateDateTime, "Sector.UpdateDateTime" ) ;
			base.AssertAreEqual( newobj.DeletionIndicator, oldobj.DeletionIndicator, "Sector.DeletionIndicator" ) ;
		 
		}
	}

}

