
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

using nu = NUnit.Framework;
using t = alby.pantheon.codegen.table ;

namespace alby.pantheon.codegen.test
{
	public partial class CodeGenUnitTestClass : acr.CodeGenUnitTestBase
	{
		protected void PopulateOverride٠FitoutDetail( bool insert, t.FitoutDetail obj )
		{
			if ( insert )
			{
				// obj.FitoutDetailID = null ;
				// obj.FitoutContribution = null ;
				// obj.FitoutPeriod = null ;
				// obj.IncentiveBudget = null ;
				// obj.HandoverDate = null ;
				// obj.ArchitectFeesPayableIndicator = null ;
				// obj.ArchitectFees = null ;
				// obj.EngineerFeesPayableIndicator = null ;
				// obj.EngineerFees = null ;
				// obj.SmallShopDesignerFeesPayableIndicator = null ;
				// obj.SmallShopDesignerFees = null ;
				// obj.SurveyFeePayableIndicator = null ;
				// obj.SurveyFees = null ;
				// obj.TenantCoordinationFeesPayable = null ;
				// obj.TenantCoordinationFees = null ;
				// obj.AgreementToLeaseIndicator = null ;
				// obj.DevelopmentApprovalsRequiredIndicator = null ;
				// obj.DevelopmentApprovalsDueDate = null ;
				// obj.ConceptPlanSubmitDate = null ;
				// obj.FullWorkingDrawingsSubmitDate = null ;
				// obj.PracticalCompletionDateLessor = null ;
				// obj.EstimatedOpeningDate = null ;
				// obj.RefurbishmentRequiredIndicator = null ;
				// obj.FitoutPlanSubmitDate = null ;
				// obj.PracticalCompletionDateLessee = null ;
				// obj.DevelopmentDesignFormSubmitDate = null ;
				// obj.LessorWorksCost = null ;
				// obj.UpdateUserCode = null ;
				// obj.UpdateDateTime = null ;
				// obj.SmallShopDesignerLessorFee = null ;
				// obj.SmallShopDesignerBillingDate = null ;
			}
			else // update
			{
				// obj.FitoutDetailID = null ;
				// obj.FitoutContribution = null ;
				// obj.FitoutPeriod = null ;
				// obj.IncentiveBudget = null ;
				// obj.HandoverDate = null ;
				// obj.ArchitectFeesPayableIndicator = null ;
				// obj.ArchitectFees = null ;
				// obj.EngineerFeesPayableIndicator = null ;
				// obj.EngineerFees = null ;
				// obj.SmallShopDesignerFeesPayableIndicator = null ;
				// obj.SmallShopDesignerFees = null ;
				// obj.SurveyFeePayableIndicator = null ;
				// obj.SurveyFees = null ;
				// obj.TenantCoordinationFeesPayable = null ;
				// obj.TenantCoordinationFees = null ;
				// obj.AgreementToLeaseIndicator = null ;
				// obj.DevelopmentApprovalsRequiredIndicator = null ;
				// obj.DevelopmentApprovalsDueDate = null ;
				// obj.ConceptPlanSubmitDate = null ;
				// obj.FullWorkingDrawingsSubmitDate = null ;
				// obj.PracticalCompletionDateLessor = null ;
				// obj.EstimatedOpeningDate = null ;
				// obj.RefurbishmentRequiredIndicator = null ;
				// obj.FitoutPlanSubmitDate = null ;
				// obj.PracticalCompletionDateLessee = null ;
				// obj.DevelopmentDesignFormSubmitDate = null ;
				// obj.LessorWorksCost = null ;
				// obj.UpdateUserCode = null ;
				// obj.UpdateDateTime = null ;
				// obj.SmallShopDesignerLessorFee = null ;
				// obj.SmallShopDesignerBillingDate = null ;
			}
			 
		}
	}

}

