
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

using nu = NUnit.Framework;
using t = alby.pantheon.codegen.table ;

namespace alby.pantheon.codegen.test
{
	public partial class CodeGenUnitTestClass : acr.CodeGenUnitTestBase
	{
		protected void Assert٠SurrenderDetail( bool insert, t.SurrenderDetail newobj, t.SurrenderDetail oldobj )
		{
			acr.CodeGenEtc.ConsoleMessage( ! this.QuietMode, "[20/40] SurrenderDetail - assert" ) ;
		 
			nu.Assert.IsNotNull( newobj.SurrenderDetailID, "SurrenderDetail.SurrenderDetailID" ) ;
			nu.Assert.IsNotNull( newobj.TenantSolicitorName, "SurrenderDetail.TenantSolicitorName" ) ;
			nu.Assert.IsNotNull( newobj.TenantName, "SurrenderDetail.TenantName" ) ;
			nu.Assert.IsNotNull( newobj.TenantShopNo, "SurrenderDetail.TenantShopNo" ) ;
			nu.Assert.IsNotNull( newobj.TenantSurrenderApplicable, "SurrenderDetail.TenantSurrenderApplicable" ) ;
			nu.Assert.IsNotNull( newobj.TenantSurrenderDate, "SurrenderDetail.TenantSurrenderDate" ) ;
			nu.Assert.IsNotNull( newobj.TenantSurrenderSumPayableByLessee, "SurrenderDetail.TenantSurrenderSumPayableByLessee" ) ;
			nu.Assert.IsNotNull( newobj.TenantSurrenderSumPayableByLessor, "SurrenderDetail.TenantSurrenderSumPayableByLessor" ) ;
			nu.Assert.IsNotNull( newobj.TenantMakeGoodRequiredIndicator, "SurrenderDetail.TenantMakeGoodRequiredIndicator" ) ;
			nu.Assert.IsNotNull( newobj.TenantLeaseNumber, "SurrenderDetail.TenantLeaseNumber" ) ;
			nu.Assert.IsNotNull( newobj.TenantLeaseDate, "SurrenderDetail.TenantLeaseDate" ) ;
			nu.Assert.IsNotNull( newobj.TenantSendDocsTo, "SurrenderDetail.TenantSendDocsTo" ) ;
			nu.Assert.IsNotNull( newobj.LesseeSolicitorName, "SurrenderDetail.LesseeSolicitorName" ) ;
			nu.Assert.IsNotNull( newobj.LesseeName, "SurrenderDetail.LesseeName" ) ;
			nu.Assert.IsNotNull( newobj.LesseeShopNo, "SurrenderDetail.LesseeShopNo" ) ;
			nu.Assert.IsNotNull( newobj.LesseeSurrenderApplicable, "SurrenderDetail.LesseeSurrenderApplicable" ) ;
			nu.Assert.IsNotNull( newobj.LesseeSurrenderDate, "SurrenderDetail.LesseeSurrenderDate" ) ;
			nu.Assert.IsNotNull( newobj.LesseeSurrenderSumPayableByLessee, "SurrenderDetail.LesseeSurrenderSumPayableByLessee" ) ;
			nu.Assert.IsNotNull( newobj.LesseeSurrenderSumPayableByLessor, "SurrenderDetail.LesseeSurrenderSumPayableByLessor" ) ;
			nu.Assert.IsNotNull( newobj.LesseeMakeGoodRequiredIndicator, "SurrenderDetail.LesseeMakeGoodRequiredIndicator" ) ;
			nu.Assert.IsNotNull( newobj.LesseeLeaseNumber, "SurrenderDetail.LesseeLeaseNumber" ) ;
			nu.Assert.IsNotNull( newobj.LesseeLeaseDate, "SurrenderDetail.LesseeLeaseDate" ) ;
			nu.Assert.IsNotNull( newobj.LesseeSendDocsTo, "SurrenderDetail.LesseeSendDocsTo" ) ;
			nu.Assert.IsNotNull( newobj.UpdateUserCode, "SurrenderDetail.UpdateUserCode" ) ;
			nu.Assert.IsNotNull( newobj.UpdateDateTime, "SurrenderDetail.UpdateDateTime" ) ;
			nu.Assert.IsNotNull( newobj.RowTimestamp, "SurrenderDetail.RowTimestamp" ) ;
			nu.Assert.IsNotNull( newobj.TenantTradingName, "SurrenderDetail.TenantTradingName" ) ;
			nu.Assert.IsNotNull( newobj.LesseeTradingName, "SurrenderDetail.LesseeTradingName" ) ;
			nu.Assert.IsNotNull( newobj.LesseeLiableLegalFeesIndicator, "SurrenderDetail.LesseeLiableLegalFeesIndicator" ) ;
		 
			base.AssertAreEqual( newobj.SurrenderDetailID, oldobj.SurrenderDetailID, "SurrenderDetail.SurrenderDetailID" ) ;
			base.AssertAreEqual( newobj.TenantSolicitorName, oldobj.TenantSolicitorName, "SurrenderDetail.TenantSolicitorName" ) ;
			base.AssertAreEqual( newobj.TenantName, oldobj.TenantName, "SurrenderDetail.TenantName" ) ;
			base.AssertAreEqual( newobj.TenantShopNo, oldobj.TenantShopNo, "SurrenderDetail.TenantShopNo" ) ;
			base.AssertAreEqual( newobj.TenantSurrenderApplicable, oldobj.TenantSurrenderApplicable, "SurrenderDetail.TenantSurrenderApplicable" ) ;
			base.AssertAreEqual( newobj.TenantSurrenderDate, oldobj.TenantSurrenderDate, "SurrenderDetail.TenantSurrenderDate" ) ;
			base.AssertAreEqual( newobj.TenantSurrenderSumPayableByLessee, oldobj.TenantSurrenderSumPayableByLessee, "SurrenderDetail.TenantSurrenderSumPayableByLessee" ) ;
			base.AssertAreEqual( newobj.TenantSurrenderSumPayableByLessor, oldobj.TenantSurrenderSumPayableByLessor, "SurrenderDetail.TenantSurrenderSumPayableByLessor" ) ;
			base.AssertAreEqual( newobj.TenantMakeGoodRequiredIndicator, oldobj.TenantMakeGoodRequiredIndicator, "SurrenderDetail.TenantMakeGoodRequiredIndicator" ) ;
			base.AssertAreEqual( newobj.TenantLeaseNumber, oldobj.TenantLeaseNumber, "SurrenderDetail.TenantLeaseNumber" ) ;
			base.AssertAreEqual( newobj.TenantLeaseDate, oldobj.TenantLeaseDate, "SurrenderDetail.TenantLeaseDate" ) ;
			base.AssertAreEqual( newobj.TenantSendDocsTo, oldobj.TenantSendDocsTo, "SurrenderDetail.TenantSendDocsTo" ) ;
			base.AssertAreEqual( newobj.LesseeSolicitorName, oldobj.LesseeSolicitorName, "SurrenderDetail.LesseeSolicitorName" ) ;
			base.AssertAreEqual( newobj.LesseeName, oldobj.LesseeName, "SurrenderDetail.LesseeName" ) ;
			base.AssertAreEqual( newobj.LesseeShopNo, oldobj.LesseeShopNo, "SurrenderDetail.LesseeShopNo" ) ;
			base.AssertAreEqual( newobj.LesseeSurrenderApplicable, oldobj.LesseeSurrenderApplicable, "SurrenderDetail.LesseeSurrenderApplicable" ) ;
			base.AssertAreEqual( newobj.LesseeSurrenderDate, oldobj.LesseeSurrenderDate, "SurrenderDetail.LesseeSurrenderDate" ) ;
			base.AssertAreEqual( newobj.LesseeSurrenderSumPayableByLessee, oldobj.LesseeSurrenderSumPayableByLessee, "SurrenderDetail.LesseeSurrenderSumPayableByLessee" ) ;
			base.AssertAreEqual( newobj.LesseeSurrenderSumPayableByLessor, oldobj.LesseeSurrenderSumPayableByLessor, "SurrenderDetail.LesseeSurrenderSumPayableByLessor" ) ;
			base.AssertAreEqual( newobj.LesseeMakeGoodRequiredIndicator, oldobj.LesseeMakeGoodRequiredIndicator, "SurrenderDetail.LesseeMakeGoodRequiredIndicator" ) ;
			base.AssertAreEqual( newobj.LesseeLeaseNumber, oldobj.LesseeLeaseNumber, "SurrenderDetail.LesseeLeaseNumber" ) ;
			base.AssertAreEqual( newobj.LesseeLeaseDate, oldobj.LesseeLeaseDate, "SurrenderDetail.LesseeLeaseDate" ) ;
			base.AssertAreEqual( newobj.LesseeSendDocsTo, oldobj.LesseeSendDocsTo, "SurrenderDetail.LesseeSendDocsTo" ) ;
			base.AssertAreEqual( newobj.UpdateUserCode, oldobj.UpdateUserCode, "SurrenderDetail.UpdateUserCode" ) ;
			base.AssertAreEqual( newobj.UpdateDateTime, oldobj.UpdateDateTime, "SurrenderDetail.UpdateDateTime" ) ;
			base.AssertAreEqual( newobj.TenantTradingName, oldobj.TenantTradingName, "SurrenderDetail.TenantTradingName" ) ;
			base.AssertAreEqual( newobj.LesseeTradingName, oldobj.LesseeTradingName, "SurrenderDetail.LesseeTradingName" ) ;
			base.AssertAreEqual( newobj.LesseeLiableLegalFeesIndicator, oldobj.LesseeLiableLegalFeesIndicator, "SurrenderDetail.LesseeLiableLegalFeesIndicator" ) ;
		 
		}
	}

}

