
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

using nu = NUnit.Framework;
using t = alby.pantheon.codegen.table ;

namespace alby.pantheon.codegen.test
{
	public partial class CodeGenUnitTestClass : acr.CodeGenUnitTestBase
	{
		protected void Populate٠RentDetail( bool insert, t.RentDetail obj )
		{
			if ( insert )
			{
				obj.RentDetailID = toint( factory٠RentDetailFactory.GetNextIdˡ( _connection, t.RentDetail.column٠RentDetailID, true ).ToString() ) ;
				obj.BaseRent = -1.0m ;
				obj.BaseRentSQM = -1.0m ;
				obj.BudgetedBaseRent = -1.0m ;
				obj.CurrentBaseRent = -1.0m ;
				obj.PercentageRent = -1.0m ;
				obj.PercentageRentText = "@" ;
				obj.MarketingLevy = -1.0m ;
				obj.SpecialOpeningPromotionLevy = -1.0m ;
				obj.MonthlyRent = -1.0m ;
				obj.RentPaymentCommencementDate = new DateTime(1900,1,1) ;
				obj.RentPaymentCommencementDateText = "@" ;
				obj.MarketingLevyPaymentCommencementDate = new DateTime(1900,1,1) ;
				obj.MarketingLevyPaymentCommencementDateText = "@" ;
				obj.RentReviewID = obj1٠RentReview != null ? obj1٠RentReview.RentReviewID : obj0٠RentReview.RentReviewID ;
				obj.RentFreePeriod = -100 ;
				obj.DirectorsPersonalGuaranteeIndicator = "@" ;
				obj.BaseRentPayableIndicator = "@" ;
				obj.OutgoingsPayableIndicator = "@" ;
				obj.MarketingLevyPayableIndicator = "@" ;
				obj.BankGuaranteeRequiredIndicator = "@" ;
				obj.BankGuaranteeAmount = -1.0m ;
				obj.BankGuaranteeAmountCalculated = -1.0m ;
				obj.ReducedBankGuaranteeAmount = -1.0m ;
				obj.BankGuaranteeRequiredLesseeIndicator = "@" ;
				obj.ActualBankGuaranteeAmount = -1.0m ;
				obj.OptionRequiredIndicator = "@" ;
				obj.OptionTermYears = -100 ;
				obj.OptionTermMonths = -100 ;
				obj.OptionTermDays = -100 ;
				obj.OptionTermText = "@" ;
				obj.AtOptionRentReviewTypeID = obj1٠RentReviewType != null ? obj1٠RentReviewType.RentReviewTypeID : obj0٠RentReviewType.RentReviewTypeID ;
				obj.DuringOptionRentReviewTypeID = obj1٠RentReviewType != null ? obj1٠RentReviewType.RentReviewTypeID : obj0٠RentReviewType.RentReviewTypeID ;
				obj.UpdateUserCode = "@" ;
				obj.UpdateDateTime = new DateTime(1900,1,1) ;
				obj.ConsumerPriceIndexDescriptionAtOption = "@" ;
				obj.ConsumerPriceIndexDescriptionDuringOption = "@" ;
				obj.RentReviewIncreaseAtOption = -1.0m ;
				obj.RentReviewIncreaseDuringOption = -1.0m ;
			}
			else // update
			{
				obj.BaseRent = -2.0m ;
				obj.BaseRentSQM = -2.0m ;
				obj.BudgetedBaseRent = -2.0m ;
				obj.CurrentBaseRent = -2.0m ;
				obj.PercentageRent = -2.0m ;
				obj.PercentageRentText = "#" ;
				obj.MarketingLevy = -2.0m ;
				obj.SpecialOpeningPromotionLevy = -2.0m ;
				obj.MonthlyRent = -2.0m ;
				obj.RentPaymentCommencementDate = new DateTime(1901,12,31) ;
				obj.RentPaymentCommencementDateText = "#" ;
				obj.MarketingLevyPaymentCommencementDate = new DateTime(1901,12,31) ;
				obj.MarketingLevyPaymentCommencementDateText = "#" ;
				obj.RentFreePeriod = -200 ;
				obj.DirectorsPersonalGuaranteeIndicator = "#" ;
				obj.BaseRentPayableIndicator = "#" ;
				obj.OutgoingsPayableIndicator = "#" ;
				obj.MarketingLevyPayableIndicator = "#" ;
				obj.BankGuaranteeRequiredIndicator = "#" ;
				obj.BankGuaranteeAmount = -2.0m ;
				obj.BankGuaranteeAmountCalculated = -2.0m ;
				obj.ReducedBankGuaranteeAmount = -2.0m ;
				obj.BankGuaranteeRequiredLesseeIndicator = "#" ;
				obj.ActualBankGuaranteeAmount = -2.0m ;
				obj.OptionRequiredIndicator = "#" ;
				obj.OptionTermYears = -200 ;
				obj.OptionTermMonths = -200 ;
				obj.OptionTermDays = -200 ;
				obj.OptionTermText = "#" ;
				obj.UpdateUserCode = "#" ;
				obj.UpdateDateTime = new DateTime(1901,12,31) ;
				obj.ConsumerPriceIndexDescriptionAtOption = "#" ;
				obj.ConsumerPriceIndexDescriptionDuringOption = "#" ;
				obj.RentReviewIncreaseAtOption = -2.0m ;
				obj.RentReviewIncreaseDuringOption = -2.0m ;
			}
			 
		}
	}

}

