
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

using nu = NUnit.Framework;
using t = alby.pantheon.codegen.table ;

namespace alby.pantheon.codegen.test
{
	public partial class CodeGenUnitTestClass : acr.CodeGenUnitTestBase
	{
		protected void Assert٠Franchise( bool insert, t.Franchise newobj, t.Franchise oldobj )
		{
			acr.CodeGenEtc.ConsoleMessage( ! this.QuietMode, "[28/40] Franchise - assert" ) ;
		 
			nu.Assert.IsNotNull( newobj.PartyID, "Franchise.PartyID" ) ;
			nu.Assert.IsNotNull( newobj.DisplayOrder, "Franchise.DisplayOrder" ) ;
			nu.Assert.IsNotNull( newobj.UpdateUserCode, "Franchise.UpdateUserCode" ) ;
			nu.Assert.IsNotNull( newobj.UpdateDateTime, "Franchise.UpdateDateTime" ) ;
			nu.Assert.IsNotNull( newobj.RowTimestamp, "Franchise.RowTimestamp" ) ;
		 
			base.AssertAreEqual( newobj.PartyID, oldobj.PartyID, "Franchise.PartyID" ) ;
			base.AssertAreEqual( newobj.DisplayOrder, oldobj.DisplayOrder, "Franchise.DisplayOrder" ) ;
			base.AssertAreEqual( newobj.UpdateUserCode, oldobj.UpdateUserCode, "Franchise.UpdateUserCode" ) ;
			base.AssertAreEqual( newobj.UpdateDateTime, oldobj.UpdateDateTime, "Franchise.UpdateDateTime" ) ;
		 
		}
	}

}

