
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

using nu = NUnit.Framework;
using t = alby.pantheon.codegen.table ;

namespace alby.pantheon.codegen.test
{
	public partial class CodeGenUnitTestClass : acr.CodeGenUnitTestBase
	{
		protected void Populate٠Lease( bool insert, t.Lease obj )
		{
			if ( insert )
			{
				obj.LeaseID = toint( factory٠LeaseFactory.GetNextIdˡ( _connection, t.Lease.column٠LeaseID, true ).ToString() ) ;
				obj.LeaseStatus = "@" ;
				obj.PIMSUsageCode = "@" ;
				obj.LeaseTypeID = obj1٠LeaseType != null ? obj1٠LeaseType.LeaseTypeID : obj0٠LeaseType.LeaseTypeID ;
				obj.CostCentreStageID = obj1٠CostCentreStage != null ? obj1٠CostCentreStage.CostCentreStageID : obj0٠CostCentreStage.CostCentreStageID ;
				obj.StageNumber = "@" ;
				obj.ShopNo = "@" ;
				obj.Level = "@" ;
				obj.Area = -1.0m ;
				obj.AreaType = "@" ;
				obj.PrecinctID = obj1٠Precinct != null ? obj1٠Precinct.PrecinctID : obj0٠Precinct.PrecinctID ;
				obj.SectorID = obj1٠Sector != null ? obj1٠Sector.SectorID : obj0٠Sector.SectorID ;
				obj.ShopTypeID = obj1٠ShopType != null ? obj1٠ShopType.ShopTypeID : obj0٠ShopType.ShopTypeID ;
				obj.LeaseExecutiveID = obj1٠LeaseExecutive != null ? obj1٠LeaseExecutive.PartyID : obj0٠LeaseExecutive.PartyID ;
				obj.LeaseGuarantorID = -100 ;
				obj.LesseeID = obj1٠Lessee != null ? obj1٠Lessee.PartyID : obj0٠Lessee.PartyID ;
				obj.SolicitorID = obj1٠Solicitor != null ? obj1٠Solicitor.PartyID : obj0٠Solicitor.PartyID ;
				obj.CommenceDate = new DateTime(1900,1,1) ;
				obj.ExpiryDate = new DateTime(1900,1,1) ;
				obj.LeaseTermYears = -100 ;
				obj.LeaseTermMonths = -100 ;
				obj.LeaseTermDays = -100 ;
				obj.LeaseTermText = "@" ;
				obj.LOIIssueDate = new DateTime(1900,1,1) ;
				obj.LOIDueDate = new DateTime(1900,1,1) ;
				obj.CompanyName = "@" ;
				obj.ACN = "@" ;
				obj.ABN = "@" ;
				obj.LesseeName = "@" ;
				obj.TradingName = "@" ;
				obj.ChainID = obj1٠Chain != null ? obj1٠Chain.ChainID : obj0٠Chain.ChainID ;
				obj.SalesCategoryID = obj1٠SalesCategory != null ? obj1٠SalesCategory.SalesCategoryID : obj0٠SalesCategory.SalesCategoryID ;
				obj.PermittedUse = "@" ;
				obj.ExpenseDetailID = obj1٠ExpenseDetail != null ? obj1٠ExpenseDetail.ExpenseDetailID : obj0٠ExpenseDetail.ExpenseDetailID ;
				obj.FitoutDetailID = obj1٠FitoutDetail != null ? obj1٠FitoutDetail.FitoutDetailID : obj0٠FitoutDetail.FitoutDetailID ;
				obj.LeaseAdministrationID = obj1٠LeaseAdministration != null ? obj1٠LeaseAdministration.LeaseAdministrationID : obj0٠LeaseAdministration.LeaseAdministrationID ;
				obj.LeaseCommentID = obj1٠LeaseComment != null ? obj1٠LeaseComment.LeaseCommentID : obj0٠LeaseComment.LeaseCommentID ;
				obj.LeaseConditionID = obj1٠LeaseCondition != null ? obj1٠LeaseCondition.LeaseConditionID : obj0٠LeaseCondition.LeaseConditionID ;
				obj.RentDetailID = obj1٠RentDetail != null ? obj1٠RentDetail.RentDetailID : obj0٠RentDetail.RentDetailID ;
				obj.SurrenderDetailID = obj1٠SurrenderDetail != null ? obj1٠SurrenderDetail.SurrenderDetailID : obj0٠SurrenderDetail.SurrenderDetailID ;
				obj.VacantPossessionDetailID = obj1٠VacantPossessionDetail != null ? obj1٠VacantPossessionDetail.VacantPossessionDetailID : obj0٠VacantPossessionDetail.VacantPossessionDetailID ;
				obj.UpdateUserCode = "@" ;
				obj.UpdateDateTime = new DateTime(1900,1,1) ;
			}
			else // update
			{
				obj.LeaseStatus = "#" ;
				obj.PIMSUsageCode = "#" ;
				obj.StageNumber = "#" ;
				obj.ShopNo = "#" ;
				obj.Level = "#" ;
				obj.Area = -2.0m ;
				obj.AreaType = "#" ;
				obj.LeaseGuarantorID = -200 ;
				obj.CommenceDate = new DateTime(1901,12,31) ;
				obj.ExpiryDate = new DateTime(1901,12,31) ;
				obj.LeaseTermYears = -200 ;
				obj.LeaseTermMonths = -200 ;
				obj.LeaseTermDays = -200 ;
				obj.LeaseTermText = "#" ;
				obj.LOIIssueDate = new DateTime(1901,12,31) ;
				obj.LOIDueDate = new DateTime(1901,12,31) ;
				obj.CompanyName = "#" ;
				obj.ACN = "#" ;
				obj.ABN = "#" ;
				obj.LesseeName = "#" ;
				obj.TradingName = "#" ;
				obj.PermittedUse = "#" ;
				obj.UpdateUserCode = "#" ;
				obj.UpdateDateTime = new DateTime(1901,12,31) ;
			}
			 
		}
	}

}

