
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

using nu = NUnit.Framework;
using t = alby.pantheon.codegen.table ;

namespace alby.pantheon.codegen.test
{
	public partial class CodeGenUnitTestClass : acr.CodeGenUnitTestBase
	{
		protected void Assert٠Centre( bool insert, t.Centre newobj, t.Centre oldobj )
		{
			acr.CodeGenEtc.ConsoleMessage( ! this.QuietMode, "[23/40] Centre - assert" ) ;
		 
			nu.Assert.IsNotNull( newobj.PartyID, "Centre.PartyID" ) ;
			nu.Assert.IsNotNull( newobj.CentreCode, "Centre.CentreCode" ) ;
			nu.Assert.IsNotNull( newobj.CentreName, "Centre.CentreName" ) ;
			nu.Assert.IsNotNull( newobj.CentreManagerName, "Centre.CentreManagerName" ) ;
			nu.Assert.IsNotNull( newobj.UpdateUserCode, "Centre.UpdateUserCode" ) ;
			nu.Assert.IsNotNull( newobj.UpdateDateTime, "Centre.UpdateDateTime" ) ;
			nu.Assert.IsNotNull( newobj.RowTimestamp, "Centre.RowTimestamp" ) ;
			nu.Assert.IsNotNull( newobj.SolicitorWebServiceGUID, "Centre.SolicitorWebServiceGUID" ) ;
		 
			base.AssertAreEqual( newobj.PartyID, oldobj.PartyID, "Centre.PartyID" ) ;
			base.AssertAreEqual( newobj.CentreCode, oldobj.CentreCode, "Centre.CentreCode" ) ;
			base.AssertAreEqual( newobj.CentreName, oldobj.CentreName, "Centre.CentreName" ) ;
			base.AssertAreEqual( newobj.CentreManagerName, oldobj.CentreManagerName, "Centre.CentreManagerName" ) ;
			base.AssertAreEqual( newobj.UpdateUserCode, oldobj.UpdateUserCode, "Centre.UpdateUserCode" ) ;
			base.AssertAreEqual( newobj.UpdateDateTime, oldobj.UpdateDateTime, "Centre.UpdateDateTime" ) ;
			base.AssertAreEqual( newobj.SolicitorWebServiceGUID, oldobj.SolicitorWebServiceGUID, "Centre.SolicitorWebServiceGUID" ) ;
		 
		}
	}

}

