
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

using nu = NUnit.Framework;
using t = alby.pantheon.codegen.table ;

namespace alby.pantheon.codegen.test
{
	public partial class CodeGenUnitTestClass : acr.CodeGenUnitTestBase
	{
		protected void Assert٠LeaseComment( bool insert, t.LeaseComment newobj, t.LeaseComment oldobj )
		{
			acr.CodeGenEtc.ConsoleMessage( ! this.QuietMode, "[8/40] LeaseComment - assert" ) ;
		 
			nu.Assert.IsNotNull( newobj.LeaseCommentID, "LeaseComment.LeaseCommentID" ) ;
			nu.Assert.IsNotNull( newobj.GeneralComment, "LeaseComment.GeneralComment" ) ;
			nu.Assert.IsNotNull( newobj.UpdateUserCode, "LeaseComment.UpdateUserCode" ) ;
			nu.Assert.IsNotNull( newobj.UpdateDateTime, "LeaseComment.UpdateDateTime" ) ;
			nu.Assert.IsNotNull( newobj.RowTimestamp, "LeaseComment.RowTimestamp" ) ;
		 
			base.AssertAreEqual( newobj.LeaseCommentID, oldobj.LeaseCommentID, "LeaseComment.LeaseCommentID" ) ;
			base.AssertAreEqual( newobj.GeneralComment, oldobj.GeneralComment, "LeaseComment.GeneralComment" ) ;
			base.AssertAreEqual( newobj.UpdateUserCode, oldobj.UpdateUserCode, "LeaseComment.UpdateUserCode" ) ;
			base.AssertAreEqual( newobj.UpdateDateTime, oldobj.UpdateDateTime, "LeaseComment.UpdateDateTime" ) ;
		 
		}
	}

}

