
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

using nu = NUnit.Framework;
using t = alby.pantheon.codegen.table ;

namespace alby.pantheon.codegen.test
{
	public partial class CodeGenUnitTestClass : acr.CodeGenUnitTestBase
	{
		protected void Assert٠Lease( bool insert, t.Lease newobj, t.Lease oldobj )
		{
			acr.CodeGenEtc.ConsoleMessage( ! this.QuietMode, "[38/40] Lease - assert" ) ;
		 
			nu.Assert.IsNotNull( newobj.LeaseID, "Lease.LeaseID" ) ;
			nu.Assert.IsNotNull( newobj.LeaseStatus, "Lease.LeaseStatus" ) ;
			nu.Assert.IsNotNull( newobj.PIMSUsageCode, "Lease.PIMSUsageCode" ) ;
			nu.Assert.IsNotNull( newobj.LeaseTypeID, "Lease.LeaseTypeID" ) ;
			nu.Assert.IsNotNull( newobj.CostCentreStageID, "Lease.CostCentreStageID" ) ;
			nu.Assert.IsNotNull( newobj.StageNumber, "Lease.StageNumber" ) ;
			nu.Assert.IsNotNull( newobj.ShopNo, "Lease.ShopNo" ) ;
			nu.Assert.IsNotNull( newobj.Level, "Lease.Level" ) ;
			nu.Assert.IsNotNull( newobj.Area, "Lease.Area" ) ;
			nu.Assert.IsNotNull( newobj.AreaType, "Lease.AreaType" ) ;
			nu.Assert.IsNotNull( newobj.PrecinctID, "Lease.PrecinctID" ) ;
			nu.Assert.IsNotNull( newobj.SectorID, "Lease.SectorID" ) ;
			nu.Assert.IsNotNull( newobj.ShopTypeID, "Lease.ShopTypeID" ) ;
			nu.Assert.IsNotNull( newobj.LeaseExecutiveID, "Lease.LeaseExecutiveID" ) ;
			nu.Assert.IsNotNull( newobj.LeaseGuarantorID, "Lease.LeaseGuarantorID" ) ;
			nu.Assert.IsNotNull( newobj.LesseeID, "Lease.LesseeID" ) ;
			nu.Assert.IsNotNull( newobj.SolicitorID, "Lease.SolicitorID" ) ;
			nu.Assert.IsNotNull( newobj.CommenceDate, "Lease.CommenceDate" ) ;
			nu.Assert.IsNotNull( newobj.ExpiryDate, "Lease.ExpiryDate" ) ;
			nu.Assert.IsNotNull( newobj.LeaseTermYears, "Lease.LeaseTermYears" ) ;
			nu.Assert.IsNotNull( newobj.LeaseTermMonths, "Lease.LeaseTermMonths" ) ;
			nu.Assert.IsNotNull( newobj.LeaseTermDays, "Lease.LeaseTermDays" ) ;
			nu.Assert.IsNotNull( newobj.LeaseTermText, "Lease.LeaseTermText" ) ;
			nu.Assert.IsNotNull( newobj.LOIIssueDate, "Lease.LOIIssueDate" ) ;
			nu.Assert.IsNotNull( newobj.LOIDueDate, "Lease.LOIDueDate" ) ;
			nu.Assert.IsNotNull( newobj.CompanyName, "Lease.CompanyName" ) ;
			nu.Assert.IsNotNull( newobj.ACN, "Lease.ACN" ) ;
			nu.Assert.IsNotNull( newobj.ABN, "Lease.ABN" ) ;
			nu.Assert.IsNotNull( newobj.LesseeName, "Lease.LesseeName" ) ;
			nu.Assert.IsNotNull( newobj.TradingName, "Lease.TradingName" ) ;
			nu.Assert.IsNotNull( newobj.ChainID, "Lease.ChainID" ) ;
			nu.Assert.IsNotNull( newobj.SalesCategoryID, "Lease.SalesCategoryID" ) ;
			nu.Assert.IsNotNull( newobj.PermittedUse, "Lease.PermittedUse" ) ;
			nu.Assert.IsNotNull( newobj.ExpenseDetailID, "Lease.ExpenseDetailID" ) ;
			nu.Assert.IsNotNull( newobj.FitoutDetailID, "Lease.FitoutDetailID" ) ;
			nu.Assert.IsNotNull( newobj.LeaseAdministrationID, "Lease.LeaseAdministrationID" ) ;
			nu.Assert.IsNotNull( newobj.LeaseCommentID, "Lease.LeaseCommentID" ) ;
			nu.Assert.IsNotNull( newobj.LeaseConditionID, "Lease.LeaseConditionID" ) ;
			nu.Assert.IsNotNull( newobj.RentDetailID, "Lease.RentDetailID" ) ;
			nu.Assert.IsNotNull( newobj.SurrenderDetailID, "Lease.SurrenderDetailID" ) ;
			nu.Assert.IsNotNull( newobj.VacantPossessionDetailID, "Lease.VacantPossessionDetailID" ) ;
			nu.Assert.IsNotNull( newobj.UpdateUserCode, "Lease.UpdateUserCode" ) ;
			nu.Assert.IsNotNull( newobj.UpdateDateTime, "Lease.UpdateDateTime" ) ;
			nu.Assert.IsNotNull( newobj.RowTimestamp, "Lease.RowTimestamp" ) ;
		 
			base.AssertAreEqual( newobj.LeaseID, oldobj.LeaseID, "Lease.LeaseID" ) ;
			base.AssertAreEqual( newobj.LeaseStatus, oldobj.LeaseStatus, "Lease.LeaseStatus" ) ;
			base.AssertAreEqual( newobj.PIMSUsageCode, oldobj.PIMSUsageCode, "Lease.PIMSUsageCode" ) ;
			base.AssertAreEqual( newobj.LeaseTypeID, oldobj.LeaseTypeID, "Lease.LeaseTypeID" ) ;
			base.AssertAreEqual( newobj.CostCentreStageID, oldobj.CostCentreStageID, "Lease.CostCentreStageID" ) ;
			base.AssertAreEqual( newobj.StageNumber, oldobj.StageNumber, "Lease.StageNumber" ) ;
			base.AssertAreEqual( newobj.ShopNo, oldobj.ShopNo, "Lease.ShopNo" ) ;
			base.AssertAreEqual( newobj.Level, oldobj.Level, "Lease.Level" ) ;
			base.AssertAreEqual( newobj.Area, oldobj.Area, "Lease.Area" ) ;
			base.AssertAreEqual( newobj.AreaType, oldobj.AreaType, "Lease.AreaType" ) ;
			base.AssertAreEqual( newobj.PrecinctID, oldobj.PrecinctID, "Lease.PrecinctID" ) ;
			base.AssertAreEqual( newobj.SectorID, oldobj.SectorID, "Lease.SectorID" ) ;
			base.AssertAreEqual( newobj.ShopTypeID, oldobj.ShopTypeID, "Lease.ShopTypeID" ) ;
			base.AssertAreEqual( newobj.LeaseExecutiveID, oldobj.LeaseExecutiveID, "Lease.LeaseExecutiveID" ) ;
			base.AssertAreEqual( newobj.LeaseGuarantorID, oldobj.LeaseGuarantorID, "Lease.LeaseGuarantorID" ) ;
			base.AssertAreEqual( newobj.LesseeID, oldobj.LesseeID, "Lease.LesseeID" ) ;
			base.AssertAreEqual( newobj.SolicitorID, oldobj.SolicitorID, "Lease.SolicitorID" ) ;
			base.AssertAreEqual( newobj.CommenceDate, oldobj.CommenceDate, "Lease.CommenceDate" ) ;
			base.AssertAreEqual( newobj.ExpiryDate, oldobj.ExpiryDate, "Lease.ExpiryDate" ) ;
			base.AssertAreEqual( newobj.LeaseTermYears, oldobj.LeaseTermYears, "Lease.LeaseTermYears" ) ;
			base.AssertAreEqual( newobj.LeaseTermMonths, oldobj.LeaseTermMonths, "Lease.LeaseTermMonths" ) ;
			base.AssertAreEqual( newobj.LeaseTermDays, oldobj.LeaseTermDays, "Lease.LeaseTermDays" ) ;
			base.AssertAreEqual( newobj.LeaseTermText, oldobj.LeaseTermText, "Lease.LeaseTermText" ) ;
			base.AssertAreEqual( newobj.LOIIssueDate, oldobj.LOIIssueDate, "Lease.LOIIssueDate" ) ;
			base.AssertAreEqual( newobj.LOIDueDate, oldobj.LOIDueDate, "Lease.LOIDueDate" ) ;
			base.AssertAreEqual( newobj.CompanyName, oldobj.CompanyName, "Lease.CompanyName" ) ;
			base.AssertAreEqual( newobj.ACN, oldobj.ACN, "Lease.ACN" ) ;
			base.AssertAreEqual( newobj.ABN, oldobj.ABN, "Lease.ABN" ) ;
			base.AssertAreEqual( newobj.LesseeName, oldobj.LesseeName, "Lease.LesseeName" ) ;
			base.AssertAreEqual( newobj.TradingName, oldobj.TradingName, "Lease.TradingName" ) ;
			base.AssertAreEqual( newobj.ChainID, oldobj.ChainID, "Lease.ChainID" ) ;
			base.AssertAreEqual( newobj.SalesCategoryID, oldobj.SalesCategoryID, "Lease.SalesCategoryID" ) ;
			base.AssertAreEqual( newobj.PermittedUse, oldobj.PermittedUse, "Lease.PermittedUse" ) ;
			base.AssertAreEqual( newobj.ExpenseDetailID, oldobj.ExpenseDetailID, "Lease.ExpenseDetailID" ) ;
			base.AssertAreEqual( newobj.FitoutDetailID, oldobj.FitoutDetailID, "Lease.FitoutDetailID" ) ;
			base.AssertAreEqual( newobj.LeaseAdministrationID, oldobj.LeaseAdministrationID, "Lease.LeaseAdministrationID" ) ;
			base.AssertAreEqual( newobj.LeaseCommentID, oldobj.LeaseCommentID, "Lease.LeaseCommentID" ) ;
			base.AssertAreEqual( newobj.LeaseConditionID, oldobj.LeaseConditionID, "Lease.LeaseConditionID" ) ;
			base.AssertAreEqual( newobj.RentDetailID, oldobj.RentDetailID, "Lease.RentDetailID" ) ;
			base.AssertAreEqual( newobj.SurrenderDetailID, oldobj.SurrenderDetailID, "Lease.SurrenderDetailID" ) ;
			base.AssertAreEqual( newobj.VacantPossessionDetailID, oldobj.VacantPossessionDetailID, "Lease.VacantPossessionDetailID" ) ;
			base.AssertAreEqual( newobj.UpdateUserCode, oldobj.UpdateUserCode, "Lease.UpdateUserCode" ) ;
			base.AssertAreEqual( newobj.UpdateDateTime, oldobj.UpdateDateTime, "Lease.UpdateDateTime" ) ;
		 
		}
	}

}

