
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

using nu = NUnit.Framework;
using t = alby.pantheon.codegen.table ;

namespace alby.pantheon.codegen.test
{
	public partial class CodeGenUnitTestClass : acr.CodeGenUnitTestBase
	{
		protected void PopulateOverride٠Address( bool insert, t.Address obj )
		{
			if ( insert )
			{
				// obj.AddressID = null ;
				// obj.PartyID = null ;
				// obj.AddressType = null ;
				// obj.AddressLine1 = null ;
				// obj.AddressLine2 = null ;
				// obj.Suburb = null ;
				// obj.Town = null ;
				// obj.State = null ;
				// obj.Postcode = null ;
				// obj.Country = null ;
				// obj.UpdateUserCode = null ;
				// obj.UpdateDateTime = null ;
			}
			else // update
			{
				// obj.AddressID = null ;
				// obj.PartyID = null ;
				// obj.AddressType = null ;
				// obj.AddressLine1 = null ;
				// obj.AddressLine2 = null ;
				// obj.Suburb = null ;
				// obj.Town = null ;
				// obj.State = null ;
				// obj.Postcode = null ;
				// obj.Country = null ;
				// obj.UpdateUserCode = null ;
				// obj.UpdateDateTime = null ;
			}
			 
		}
	}

}

