
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

using nu = NUnit.Framework;
using t = alby.pantheon.codegen.table ;

namespace alby.pantheon.codegen.test
{
	public partial class CodeGenUnitTestClass : acr.CodeGenUnitTestBase
	{
		protected void Populate٠Party( bool insert, t.Party obj )
		{
			if ( insert )
			{
				obj.PartyID = toint( factory٠PartyFactory.GetNextIdˡ( _connection, t.Party.column٠PartyID, true ).ToString() ) ;
				obj.Salutation = "@" ;
				obj.GivenName = "@" ;
				obj.FamilyName = "@" ;
				obj.Name = "@" ;
				obj.UpdateUserCode = "@" ;
				obj.UpdateDateTime = new DateTime(1900,1,1) ;
			}
			else // update
			{
				obj.Salutation = "#" ;
				obj.GivenName = "#" ;
				obj.FamilyName = "#" ;
				obj.Name = "#" ;
				obj.UpdateUserCode = "#" ;
				obj.UpdateDateTime = new DateTime(1901,12,31) ;
			}
			 
		}
	}

}

