
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

using nu = NUnit.Framework;
using t = alby.pantheon.codegen.table ;

namespace alby.pantheon.codegen.test
{
	public partial class CodeGenUnitTestClass : acr.CodeGenUnitTestBase
	{
		protected void Populate٠ConsumerPriceIndexRentReview( bool insert, t.ConsumerPriceIndexRentReview obj )
		{
			if ( insert )
			{
				obj.RentReviewID = obj1٠RentReview != null ? obj1٠RentReview.RentReviewID : obj0٠RentReview.RentReviewID ;
				obj.ConsumerPriceIndexDescription = "@" ;
				obj.ConsumerPriceIndexIncrease = -1.0m ;
				obj.UpdateUserCode = "@" ;
				obj.UpdateDateTime = new DateTime(1900,1,1) ;
			}
			else // update
			{
				obj.ConsumerPriceIndexDescription = "#" ;
				obj.ConsumerPriceIndexIncrease = -2.0m ;
				obj.UpdateUserCode = "#" ;
				obj.UpdateDateTime = new DateTime(1901,12,31) ;
			}
			 
		}
	}

}

