
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

using nu = NUnit.Framework;
using t = alby.pantheon.codegen.table ;

namespace alby.pantheon.codegen.test
{
	public partial class CodeGenUnitTestClass : acr.CodeGenUnitTestBase
	{
		protected void Assert٠Solicitor( bool insert, t.Solicitor newobj, t.Solicitor oldobj )
		{
			acr.CodeGenEtc.ConsoleMessage( ! this.QuietMode, "[35/40] Solicitor - assert" ) ;
		 
			nu.Assert.IsNotNull( newobj.PartyID, "Solicitor.PartyID" ) ;
			nu.Assert.IsNotNull( newobj.DisplayOrder, "Solicitor.DisplayOrder" ) ;
			nu.Assert.IsNotNull( newobj.UpdateUserCode, "Solicitor.UpdateUserCode" ) ;
			nu.Assert.IsNotNull( newobj.UpdateDateTime, "Solicitor.UpdateDateTime" ) ;
			nu.Assert.IsNotNull( newobj.RowTimestamp, "Solicitor.RowTimestamp" ) ;
		 
			base.AssertAreEqual( newobj.PartyID, oldobj.PartyID, "Solicitor.PartyID" ) ;
			base.AssertAreEqual( newobj.DisplayOrder, oldobj.DisplayOrder, "Solicitor.DisplayOrder" ) ;
			base.AssertAreEqual( newobj.UpdateUserCode, oldobj.UpdateUserCode, "Solicitor.UpdateUserCode" ) ;
			base.AssertAreEqual( newobj.UpdateDateTime, oldobj.UpdateDateTime, "Solicitor.UpdateDateTime" ) ;
		 
		}
	}

}

