
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

using nu = NUnit.Framework;
using t = alby.pantheon.codegen.table ;

namespace alby.pantheon.codegen.test
{
	public partial class CodeGenUnitTestClass : acr.CodeGenUnitTestBase
	{
		protected void Assert٠Communication( bool insert, t.Communication newobj, t.Communication oldobj )
		{
			acr.CodeGenEtc.ConsoleMessage( ! this.QuietMode, "[24/40] Communication - assert" ) ;
		 
			nu.Assert.IsNotNull( newobj.CommunicationID, "Communication.CommunicationID" ) ;
			nu.Assert.IsNotNull( newobj.PartyID, "Communication.PartyID" ) ;
			nu.Assert.IsNotNull( newobj.CommunicationTypeDescription, "Communication.CommunicationTypeDescription" ) ;
			nu.Assert.IsNotNull( newobj.CommunicationDetail, "Communication.CommunicationDetail" ) ;
			nu.Assert.IsNotNull( newobj.UpdateUserCode, "Communication.UpdateUserCode" ) ;
			nu.Assert.IsNotNull( newobj.UpdateDateTime, "Communication.UpdateDateTime" ) ;
			nu.Assert.IsNotNull( newobj.RowTimestamp, "Communication.RowTimestamp" ) ;
		 
			base.AssertAreEqual( newobj.CommunicationID, oldobj.CommunicationID, "Communication.CommunicationID" ) ;
			base.AssertAreEqual( newobj.PartyID, oldobj.PartyID, "Communication.PartyID" ) ;
			base.AssertAreEqual( newobj.CommunicationTypeDescription, oldobj.CommunicationTypeDescription, "Communication.CommunicationTypeDescription" ) ;
			base.AssertAreEqual( newobj.CommunicationDetail, oldobj.CommunicationDetail, "Communication.CommunicationDetail" ) ;
			base.AssertAreEqual( newobj.UpdateUserCode, oldobj.UpdateUserCode, "Communication.UpdateUserCode" ) ;
			base.AssertAreEqual( newobj.UpdateDateTime, oldobj.UpdateDateTime, "Communication.UpdateDateTime" ) ;
		 
		}
	}

}

