
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

using nu = NUnit.Framework;
using t = alby.pantheon.codegen.table ;

namespace alby.pantheon.codegen.test
{
	public partial class CodeGenUnitTestClass : acr.CodeGenUnitTestBase
	{
		protected void Assert٠SalesCategory( bool insert, t.SalesCategory newobj, t.SalesCategory oldobj )
		{
			acr.CodeGenEtc.ConsoleMessage( ! this.QuietMode, "[16/40] SalesCategory - assert" ) ;
		 
			nu.Assert.IsNotNull( newobj.SalesCategoryID, "SalesCategory.SalesCategoryID" ) ;
			nu.Assert.IsNotNull( newobj.SalesCategoryCode, "SalesCategory.SalesCategoryCode" ) ;
			nu.Assert.IsNotNull( newobj.SalesCategoryDescription, "SalesCategory.SalesCategoryDescription" ) ;
			nu.Assert.IsNotNull( newobj.UpdateUserCode, "SalesCategory.UpdateUserCode" ) ;
			nu.Assert.IsNotNull( newobj.UpdateDateTime, "SalesCategory.UpdateDateTime" ) ;
			nu.Assert.IsNotNull( newobj.RowTimestamp, "SalesCategory.RowTimestamp" ) ;
			nu.Assert.IsNotNull( newobj.DeletionIndicator, "SalesCategory.DeletionIndicator" ) ;
		 
			base.AssertAreEqual( newobj.SalesCategoryID, oldobj.SalesCategoryID, "SalesCategory.SalesCategoryID" ) ;
			base.AssertAreEqual( newobj.SalesCategoryCode, oldobj.SalesCategoryCode, "SalesCategory.SalesCategoryCode" ) ;
			base.AssertAreEqual( newobj.SalesCategoryDescription, oldobj.SalesCategoryDescription, "SalesCategory.SalesCategoryDescription" ) ;
			base.AssertAreEqual( newobj.UpdateUserCode, oldobj.UpdateUserCode, "SalesCategory.UpdateUserCode" ) ;
			base.AssertAreEqual( newobj.UpdateDateTime, oldobj.UpdateDateTime, "SalesCategory.UpdateDateTime" ) ;
			base.AssertAreEqual( newobj.DeletionIndicator, oldobj.DeletionIndicator, "SalesCategory.DeletionIndicator" ) ;
		 
		}
	}

}

