
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

using nu = NUnit.Framework;
using t = alby.pantheon.codegen.table ;

namespace alby.pantheon.codegen.test
{
	public partial class CodeGenUnitTestClass : acr.CodeGenUnitTestBase
	{
		protected void Assert٠ShopType( bool insert, t.ShopType newobj, t.ShopType oldobj )
		{
			acr.CodeGenEtc.ConsoleMessage( ! this.QuietMode, "[18/40] ShopType - assert" ) ;
		 
			nu.Assert.IsNotNull( newobj.ShopTypeID, "ShopType.ShopTypeID" ) ;
			nu.Assert.IsNotNull( newobj.ShopTypeDescription, "ShopType.ShopTypeDescription" ) ;
			nu.Assert.IsNotNull( newobj.UpdateUserCode, "ShopType.UpdateUserCode" ) ;
			nu.Assert.IsNotNull( newobj.UpdateDateTime, "ShopType.UpdateDateTime" ) ;
			nu.Assert.IsNotNull( newobj.RowTimestamp, "ShopType.RowTimestamp" ) ;
			nu.Assert.IsNotNull( newobj.DeletionIndicator, "ShopType.DeletionIndicator" ) ;
		 
			base.AssertAreEqual( newobj.ShopTypeID, oldobj.ShopTypeID, "ShopType.ShopTypeID" ) ;
			base.AssertAreEqual( newobj.ShopTypeDescription, oldobj.ShopTypeDescription, "ShopType.ShopTypeDescription" ) ;
			base.AssertAreEqual( newobj.UpdateUserCode, oldobj.UpdateUserCode, "ShopType.UpdateUserCode" ) ;
			base.AssertAreEqual( newobj.UpdateDateTime, oldobj.UpdateDateTime, "ShopType.UpdateDateTime" ) ;
			base.AssertAreEqual( newobj.DeletionIndicator, oldobj.DeletionIndicator, "ShopType.DeletionIndicator" ) ;
		 
		}
	}

}

