
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;
using ns = alby.pantheon.codegen;

namespace alby.pantheon.codegen.storedProcedure
{
	public partial class StoredProcedureFactory : acr.StoredProcedureFactoryBase< ns.database.pantheonDatabaseSingletonHelper, ns.database.pantheonDatabase >
	{
		public int dt_isundersourcecontrol
		(
			sds.SqlConnection connˡ, 
			string vchLoginName, 
			string vchPassword, 
			int? iWhoToo, 
			out sd.DataSet dsˡ, 
			sds.SqlTransaction tranˡ = null
		)
		{
			const string schemaˡ = "dbo" ; 
			const string spˡ = "dt_isundersourcecontrol" ; 
			 
			scg.List<sds.SqlParameter> parametersˡ = new scg.List<sds.SqlParameter>() ;
			sds.SqlParameter paramˡvchLoginName = base.AddParameterˡ( parametersˡ, "@vchLoginName", vchLoginName, sd.SqlDbType.VarChar, true, 255, null, null ) ; 
			sds.SqlParameter paramˡvchPassword = base.AddParameterˡ( parametersˡ, "@vchPassword", vchPassword, sd.SqlDbType.VarChar, true, 255, null, null ) ; 
			sds.SqlParameter paramˡiWhoToo = base.AddParameterˡ( parametersˡ, "@iWhoToo", iWhoToo, sd.SqlDbType.Int, true, null, 10, 0 ) ; 
			sds.SqlParameter paramˡrcˡ = base.AddParameterReturnValueˡ( parametersˡ, "@rcˡ" ) ; 
			 
			dsˡ = base.Executeˡ( connˡ, tranˡ, schemaˡ, spˡ, parametersˡ ) ;
			 
			return base.GetParameterValueˡ<int>( paramˡrcˡ ) ;
		}
	}

}

