
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;
using ns = alby.pantheon.codegen;

namespace alby.pantheon.codegen.storedProcedure
{
	public partial class FixedIncreaseRentReviewGet٠rs1 : acr.RowBase
	{
		public const string column٠RentReviewIncrease  = "RentReviewIncrease" ;
		public const string column٠RentReviewIncreaseText  = "RentReviewIncreaseText" ;
		public const string column٠Anniversary1  = "Anniversary1" ;
		public const string column٠Anniversary2  = "Anniversary2" ;
		public const string column٠Anniversary3  = "Anniversary3" ;
		public const string column٠Anniversary4  = "Anniversary4" ;
		public const string column٠Anniversary5  = "Anniversary5" ;
		public const string column٠Anniversary6  = "Anniversary6" ;
		public const string column٠Anniversary7  = "Anniversary7" ;
		public const string column٠Anniversary8  = "Anniversary8" ;
		public const string column٠Anniversary9  = "Anniversary9" ;
		public const string column٠RentReviewID  = "RentReviewID" ;
		public const string column٠RentReviewTypeID  = "RentReviewTypeID" ;
		public const string column٠UpdateUserCode  = "UpdateUserCode" ;
		public const string column٠UpdateDateTime  = "UpdateDateTime" ;
		public const string column٠RowTimestamp  = "RowTimestamp" ;
		 
		public decimal? RentReviewIncrease
		{
			get
			{
				return base.GetValueˡ<decimal?>( _dicˡ, column٠RentReviewIncrease ) ; 
			}
			set
			{
				base.SetValueˡ<decimal?>( _dicˡ, column٠RentReviewIncrease, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string RentReviewIncreaseText
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠RentReviewIncreaseText ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠RentReviewIncreaseText, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public decimal? Anniversary1
		{
			get
			{
				return base.GetValueˡ<decimal?>( _dicˡ, column٠Anniversary1 ) ; 
			}
			set
			{
				base.SetValueˡ<decimal?>( _dicˡ, column٠Anniversary1, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public decimal? Anniversary2
		{
			get
			{
				return base.GetValueˡ<decimal?>( _dicˡ, column٠Anniversary2 ) ; 
			}
			set
			{
				base.SetValueˡ<decimal?>( _dicˡ, column٠Anniversary2, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public decimal? Anniversary3
		{
			get
			{
				return base.GetValueˡ<decimal?>( _dicˡ, column٠Anniversary3 ) ; 
			}
			set
			{
				base.SetValueˡ<decimal?>( _dicˡ, column٠Anniversary3, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public decimal? Anniversary4
		{
			get
			{
				return base.GetValueˡ<decimal?>( _dicˡ, column٠Anniversary4 ) ; 
			}
			set
			{
				base.SetValueˡ<decimal?>( _dicˡ, column٠Anniversary4, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public decimal? Anniversary5
		{
			get
			{
				return base.GetValueˡ<decimal?>( _dicˡ, column٠Anniversary5 ) ; 
			}
			set
			{
				base.SetValueˡ<decimal?>( _dicˡ, column٠Anniversary5, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public decimal? Anniversary6
		{
			get
			{
				return base.GetValueˡ<decimal?>( _dicˡ, column٠Anniversary6 ) ; 
			}
			set
			{
				base.SetValueˡ<decimal?>( _dicˡ, column٠Anniversary6, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public decimal? Anniversary7
		{
			get
			{
				return base.GetValueˡ<decimal?>( _dicˡ, column٠Anniversary7 ) ; 
			}
			set
			{
				base.SetValueˡ<decimal?>( _dicˡ, column٠Anniversary7, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public decimal? Anniversary8
		{
			get
			{
				return base.GetValueˡ<decimal?>( _dicˡ, column٠Anniversary8 ) ; 
			}
			set
			{
				base.SetValueˡ<decimal?>( _dicˡ, column٠Anniversary8, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public decimal? Anniversary9
		{
			get
			{
				return base.GetValueˡ<decimal?>( _dicˡ, column٠Anniversary9 ) ; 
			}
			set
			{
				base.SetValueˡ<decimal?>( _dicˡ, column٠Anniversary9, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public int? RentReviewID
		{
			get
			{
				return base.GetValueˡ<int?>( _dicˡ, column٠RentReviewID ) ; 
			}
			set
			{
				base.SetValueˡ<int?>( _dicˡ, column٠RentReviewID, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public int? RentReviewTypeID
		{
			get
			{
				return base.GetValueˡ<int?>( _dicˡ, column٠RentReviewTypeID ) ; 
			}
			set
			{
				base.SetValueˡ<int?>( _dicˡ, column٠RentReviewTypeID, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string UpdateUserCode
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠UpdateUserCode ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠UpdateUserCode, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public DateTime? UpdateDateTime
		{
			get
			{
				return base.GetValueˡ<DateTime?>( _dicˡ, column٠UpdateDateTime ) ; 
			}
			set
			{
				base.SetValueˡ<DateTime?>( _dicˡ, column٠UpdateDateTime, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public byte[] RowTimestamp
		{
			get
			{
				return base.GetValueˡ<byte[]>( _dicˡ, column٠RowTimestamp ) ; 
			}
			set
			{
				base.SetValueˡ<byte[]>( _dicˡ, column٠RowTimestamp, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public FixedIncreaseRentReviewGet٠rs1() : base()
		{
			base._dicˡ[ column٠RentReviewIncrease ] = null ;
			base._dicˡ[ column٠RentReviewIncreaseText ] = null ;
			base._dicˡ[ column٠Anniversary1 ] = null ;
			base._dicˡ[ column٠Anniversary2 ] = null ;
			base._dicˡ[ column٠Anniversary3 ] = null ;
			base._dicˡ[ column٠Anniversary4 ] = null ;
			base._dicˡ[ column٠Anniversary5 ] = null ;
			base._dicˡ[ column٠Anniversary6 ] = null ;
			base._dicˡ[ column٠Anniversary7 ] = null ;
			base._dicˡ[ column٠Anniversary8 ] = null ;
			base._dicˡ[ column٠Anniversary9 ] = null ;
			base._dicˡ[ column٠RentReviewID ] = null ;
			base._dicˡ[ column٠RentReviewTypeID ] = null ;
			base._dicˡ[ column٠UpdateUserCode ] = null ;
			base._dicˡ[ column٠UpdateDateTime ] = null ;
			base._dicˡ[ column٠RowTimestamp ] = null ;
		 
		}

	}

}

