
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;
using ns = alby.pantheon.codegen;

namespace alby.pantheon.codegen.storedProcedure
{
	public partial class LeaseGet٠rs3 : acr.RowBase
	{
		public const string column٠LeaseCommentID  = "LeaseCommentID" ;
		public const string column٠GeneralComment  = "GeneralComment" ;
		public const string column٠UpdateUserCode  = "UpdateUserCode" ;
		public const string column٠UpdateDateTime  = "UpdateDateTime" ;
		public const string column٠RowTimestamp  = "RowTimestamp" ;
		 
		public int? LeaseCommentID
		{
			get
			{
				return base.GetValueˡ<int?>( _dicˡ, column٠LeaseCommentID ) ; 
			}
			set
			{
				base.SetValueˡ<int?>( _dicˡ, column٠LeaseCommentID, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string GeneralComment
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠GeneralComment ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠GeneralComment, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string UpdateUserCode
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠UpdateUserCode ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠UpdateUserCode, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public DateTime? UpdateDateTime
		{
			get
			{
				return base.GetValueˡ<DateTime?>( _dicˡ, column٠UpdateDateTime ) ; 
			}
			set
			{
				base.SetValueˡ<DateTime?>( _dicˡ, column٠UpdateDateTime, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public byte[] RowTimestamp
		{
			get
			{
				return base.GetValueˡ<byte[]>( _dicˡ, column٠RowTimestamp ) ; 
			}
			set
			{
				base.SetValueˡ<byte[]>( _dicˡ, column٠RowTimestamp, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public LeaseGet٠rs3() : base()
		{
			base._dicˡ[ column٠LeaseCommentID ] = null ;
			base._dicˡ[ column٠GeneralComment ] = null ;
			base._dicˡ[ column٠UpdateUserCode ] = null ;
			base._dicˡ[ column٠UpdateDateTime ] = null ;
			base._dicˡ[ column٠RowTimestamp ] = null ;
		 
		}

	}

}

