
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;
using ns = alby.pantheon.codegen;

namespace alby.pantheon.codegen.storedProcedure
{
	public partial class LeaseByStatus٠rs1 : acr.RowBase
	{
		public const string column٠LeaseID  = "LeaseID" ;
		public const string column٠LeaseStatus  = "LeaseStatus" ;
		public const string column٠ShopNo  = "ShopNo" ;
		public const string column٠CostCentre  = "CostCentre" ;
		public const string column٠Salutation  = "Salutation" ;
		public const string column٠GivenName  = "GivenName" ;
		public const string column٠FamilyName  = "FamilyName" ;
		public const string column٠TradingName  = "TradingName" ;
		public const string column٠CompanyName  = "CompanyName" ;
		public const string column٠UpdateUserCode  = "UpdateUserCode" ;
		public const string column٠UpdateDateTime  = "UpdateDateTime" ;
		public const string column٠RowTimestamp  = "RowTimestamp" ;
		 
		public int? LeaseID
		{
			get
			{
				return base.GetValueˡ<int?>( _dicˡ, column٠LeaseID ) ; 
			}
			set
			{
				base.SetValueˡ<int?>( _dicˡ, column٠LeaseID, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string LeaseStatus
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠LeaseStatus ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠LeaseStatus, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string ShopNo
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠ShopNo ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠ShopNo, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string CostCentre
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠CostCentre ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠CostCentre, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string Salutation
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠Salutation ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠Salutation, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string GivenName
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠GivenName ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠GivenName, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string FamilyName
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠FamilyName ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠FamilyName, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string TradingName
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠TradingName ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠TradingName, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string CompanyName
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠CompanyName ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠CompanyName, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string UpdateUserCode
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠UpdateUserCode ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠UpdateUserCode, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public DateTime? UpdateDateTime
		{
			get
			{
				return base.GetValueˡ<DateTime?>( _dicˡ, column٠UpdateDateTime ) ; 
			}
			set
			{
				base.SetValueˡ<DateTime?>( _dicˡ, column٠UpdateDateTime, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public byte[] RowTimestamp
		{
			get
			{
				return base.GetValueˡ<byte[]>( _dicˡ, column٠RowTimestamp ) ; 
			}
			set
			{
				base.SetValueˡ<byte[]>( _dicˡ, column٠RowTimestamp, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public LeaseByStatus٠rs1() : base()
		{
			base._dicˡ[ column٠LeaseID ] = null ;
			base._dicˡ[ column٠LeaseStatus ] = null ;
			base._dicˡ[ column٠ShopNo ] = null ;
			base._dicˡ[ column٠CostCentre ] = null ;
			base._dicˡ[ column٠Salutation ] = null ;
			base._dicˡ[ column٠GivenName ] = null ;
			base._dicˡ[ column٠FamilyName ] = null ;
			base._dicˡ[ column٠TradingName ] = null ;
			base._dicˡ[ column٠CompanyName ] = null ;
			base._dicˡ[ column٠UpdateUserCode ] = null ;
			base._dicˡ[ column٠UpdateDateTime ] = null ;
			base._dicˡ[ column٠RowTimestamp ] = null ;
		 
		}

	}

}

