
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;
using ns = alby.pantheon.codegen;

namespace alby.pantheon.codegen.storedProcedure
{
	public partial class LeaseExecutiveGet٠rs1 : acr.RowBase
	{
		public const string column٠AddressID  = "AddressID" ;
		public const string column٠PartyID  = "PartyID" ;
		public const string column٠AddressType  = "AddressType" ;
		public const string column٠AddressLine1  = "AddressLine1" ;
		public const string column٠AddressLine2  = "AddressLine2" ;
		public const string column٠Suburb  = "Suburb" ;
		public const string column٠Town  = "Town" ;
		public const string column٠State  = "State" ;
		public const string column٠Postcode  = "Postcode" ;
		public const string column٠Country  = "Country" ;
		public const string column٠UpdateUserCode  = "UpdateUserCode" ;
		public const string column٠UpdateDateTime  = "UpdateDateTime" ;
		public const string column٠RowTimestamp  = "RowTimestamp" ;
		 
		public int? AddressID
		{
			get
			{
				return base.GetValueˡ<int?>( _dicˡ, column٠AddressID ) ; 
			}
			set
			{
				base.SetValueˡ<int?>( _dicˡ, column٠AddressID, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public int? PartyID
		{
			get
			{
				return base.GetValueˡ<int?>( _dicˡ, column٠PartyID ) ; 
			}
			set
			{
				base.SetValueˡ<int?>( _dicˡ, column٠PartyID, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string AddressType
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠AddressType ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠AddressType, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string AddressLine1
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠AddressLine1 ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠AddressLine1, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string AddressLine2
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠AddressLine2 ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠AddressLine2, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string Suburb
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠Suburb ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠Suburb, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string Town
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠Town ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠Town, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string State
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠State ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠State, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string Postcode
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠Postcode ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠Postcode, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string Country
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠Country ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠Country, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string UpdateUserCode
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠UpdateUserCode ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠UpdateUserCode, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public DateTime? UpdateDateTime
		{
			get
			{
				return base.GetValueˡ<DateTime?>( _dicˡ, column٠UpdateDateTime ) ; 
			}
			set
			{
				base.SetValueˡ<DateTime?>( _dicˡ, column٠UpdateDateTime, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public byte[] RowTimestamp
		{
			get
			{
				return base.GetValueˡ<byte[]>( _dicˡ, column٠RowTimestamp ) ; 
			}
			set
			{
				base.SetValueˡ<byte[]>( _dicˡ, column٠RowTimestamp, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public LeaseExecutiveGet٠rs1() : base()
		{
			base._dicˡ[ column٠AddressID ] = null ;
			base._dicˡ[ column٠PartyID ] = null ;
			base._dicˡ[ column٠AddressType ] = null ;
			base._dicˡ[ column٠AddressLine1 ] = null ;
			base._dicˡ[ column٠AddressLine2 ] = null ;
			base._dicˡ[ column٠Suburb ] = null ;
			base._dicˡ[ column٠Town ] = null ;
			base._dicˡ[ column٠State ] = null ;
			base._dicˡ[ column٠Postcode ] = null ;
			base._dicˡ[ column٠Country ] = null ;
			base._dicˡ[ column٠UpdateUserCode ] = null ;
			base._dicˡ[ column٠UpdateDateTime ] = null ;
			base._dicˡ[ column٠RowTimestamp ] = null ;
		 
		}

	}

}

