
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;
using ns = alby.pantheon.codegen;

namespace alby.pantheon.codegen.storedProcedure
{
	public partial class PrecinctGet٠rs1 : acr.RowBase
	{
		public const string column٠PrecinctID  = "PrecinctID" ;
		public const string column٠PrecinctDescription  = "PrecinctDescription" ;
		public const string column٠UpdateUserCode  = "UpdateUserCode" ;
		public const string column٠UpdateDateTime  = "UpdateDateTime" ;
		public const string column٠RowTimestamp  = "RowTimestamp" ;
		public const string column٠DeletionIndicator  = "DeletionIndicator" ;
		 
		public int? PrecinctID
		{
			get
			{
				return base.GetValueˡ<int?>( _dicˡ, column٠PrecinctID ) ; 
			}
			set
			{
				base.SetValueˡ<int?>( _dicˡ, column٠PrecinctID, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string PrecinctDescription
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠PrecinctDescription ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠PrecinctDescription, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string UpdateUserCode
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠UpdateUserCode ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠UpdateUserCode, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public DateTime? UpdateDateTime
		{
			get
			{
				return base.GetValueˡ<DateTime?>( _dicˡ, column٠UpdateDateTime ) ; 
			}
			set
			{
				base.SetValueˡ<DateTime?>( _dicˡ, column٠UpdateDateTime, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public byte[] RowTimestamp
		{
			get
			{
				return base.GetValueˡ<byte[]>( _dicˡ, column٠RowTimestamp ) ; 
			}
			set
			{
				base.SetValueˡ<byte[]>( _dicˡ, column٠RowTimestamp, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string DeletionIndicator
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠DeletionIndicator ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠DeletionIndicator, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public PrecinctGet٠rs1() : base()
		{
			base._dicˡ[ column٠PrecinctID ] = null ;
			base._dicˡ[ column٠PrecinctDescription ] = null ;
			base._dicˡ[ column٠UpdateUserCode ] = null ;
			base._dicˡ[ column٠UpdateDateTime ] = null ;
			base._dicˡ[ column٠RowTimestamp ] = null ;
			base._dicˡ[ column٠DeletionIndicator ] = null ;
		 
		}

	}

}

