
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;
using ns = alby.pantheon.codegen;

namespace alby.pantheon.codegen.storedProcedure
{
	public partial class SurrenderDetailGet٠rs1 : acr.RowBase
	{
		public const string column٠SurrenderDetailID  = "SurrenderDetailID" ;
		public const string column٠TenantSolicitorName  = "TenantSolicitorName" ;
		public const string column٠TenantName  = "TenantName" ;
		public const string column٠TenantShopNo  = "TenantShopNo" ;
		public const string column٠TenantSurrenderApplicable  = "TenantSurrenderApplicable" ;
		public const string column٠TenantSurrenderDate  = "TenantSurrenderDate" ;
		public const string column٠TenantSurrenderSumPayableByLessee  = "TenantSurrenderSumPayableByLessee" ;
		public const string column٠TenantSurrenderSumPayableByLessor  = "TenantSurrenderSumPayableByLessor" ;
		public const string column٠TenantMakeGoodRequiredIndicator  = "TenantMakeGoodRequiredIndicator" ;
		public const string column٠TenantLeaseNumber  = "TenantLeaseNumber" ;
		public const string column٠TenantLeaseDate  = "TenantLeaseDate" ;
		public const string column٠TenantSendDocsTo  = "TenantSendDocsTo" ;
		public const string column٠LesseeSolicitorName  = "LesseeSolicitorName" ;
		public const string column٠LesseeName  = "LesseeName" ;
		public const string column٠LesseeShopNo  = "LesseeShopNo" ;
		public const string column٠LesseeSurrenderApplicable  = "LesseeSurrenderApplicable" ;
		public const string column٠LesseeSurrenderDate  = "LesseeSurrenderDate" ;
		public const string column٠LesseeSurrenderSumPayableByLessee  = "LesseeSurrenderSumPayableByLessee" ;
		public const string column٠LesseeSurrenderSumPayableByLessor  = "LesseeSurrenderSumPayableByLessor" ;
		public const string column٠LesseeMakeGoodRequiredIndicator  = "LesseeMakeGoodRequiredIndicator" ;
		public const string column٠LesseeLeaseNumber  = "LesseeLeaseNumber" ;
		public const string column٠LesseeLeaseDate  = "LesseeLeaseDate" ;
		public const string column٠LesseeSendDocsTo  = "LesseeSendDocsTo" ;
		public const string column٠UpdateUserCode  = "UpdateUserCode" ;
		public const string column٠UpdateDateTime  = "UpdateDateTime" ;
		public const string column٠RowTimestamp  = "RowTimestamp" ;
		public const string column٠TenantTradingName  = "TenantTradingName" ;
		public const string column٠LesseeTradingName  = "LesseeTradingName" ;
		public const string column٠LesseeLiableLegalFeesIndicator  = "LesseeLiableLegalFeesIndicator" ;
		 
		public int? SurrenderDetailID
		{
			get
			{
				return base.GetValueˡ<int?>( _dicˡ, column٠SurrenderDetailID ) ; 
			}
			set
			{
				base.SetValueˡ<int?>( _dicˡ, column٠SurrenderDetailID, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string TenantSolicitorName
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠TenantSolicitorName ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠TenantSolicitorName, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string TenantName
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠TenantName ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠TenantName, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string TenantShopNo
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠TenantShopNo ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠TenantShopNo, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string TenantSurrenderApplicable
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠TenantSurrenderApplicable ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠TenantSurrenderApplicable, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public DateTime? TenantSurrenderDate
		{
			get
			{
				return base.GetValueˡ<DateTime?>( _dicˡ, column٠TenantSurrenderDate ) ; 
			}
			set
			{
				base.SetValueˡ<DateTime?>( _dicˡ, column٠TenantSurrenderDate, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public decimal? TenantSurrenderSumPayableByLessee
		{
			get
			{
				return base.GetValueˡ<decimal?>( _dicˡ, column٠TenantSurrenderSumPayableByLessee ) ; 
			}
			set
			{
				base.SetValueˡ<decimal?>( _dicˡ, column٠TenantSurrenderSumPayableByLessee, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public decimal? TenantSurrenderSumPayableByLessor
		{
			get
			{
				return base.GetValueˡ<decimal?>( _dicˡ, column٠TenantSurrenderSumPayableByLessor ) ; 
			}
			set
			{
				base.SetValueˡ<decimal?>( _dicˡ, column٠TenantSurrenderSumPayableByLessor, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string TenantMakeGoodRequiredIndicator
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠TenantMakeGoodRequiredIndicator ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠TenantMakeGoodRequiredIndicator, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string TenantLeaseNumber
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠TenantLeaseNumber ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠TenantLeaseNumber, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public DateTime? TenantLeaseDate
		{
			get
			{
				return base.GetValueˡ<DateTime?>( _dicˡ, column٠TenantLeaseDate ) ; 
			}
			set
			{
				base.SetValueˡ<DateTime?>( _dicˡ, column٠TenantLeaseDate, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string TenantSendDocsTo
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠TenantSendDocsTo ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠TenantSendDocsTo, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string LesseeSolicitorName
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠LesseeSolicitorName ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠LesseeSolicitorName, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string LesseeName
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠LesseeName ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠LesseeName, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string LesseeShopNo
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠LesseeShopNo ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠LesseeShopNo, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string LesseeSurrenderApplicable
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠LesseeSurrenderApplicable ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠LesseeSurrenderApplicable, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public DateTime? LesseeSurrenderDate
		{
			get
			{
				return base.GetValueˡ<DateTime?>( _dicˡ, column٠LesseeSurrenderDate ) ; 
			}
			set
			{
				base.SetValueˡ<DateTime?>( _dicˡ, column٠LesseeSurrenderDate, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public decimal? LesseeSurrenderSumPayableByLessee
		{
			get
			{
				return base.GetValueˡ<decimal?>( _dicˡ, column٠LesseeSurrenderSumPayableByLessee ) ; 
			}
			set
			{
				base.SetValueˡ<decimal?>( _dicˡ, column٠LesseeSurrenderSumPayableByLessee, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public decimal? LesseeSurrenderSumPayableByLessor
		{
			get
			{
				return base.GetValueˡ<decimal?>( _dicˡ, column٠LesseeSurrenderSumPayableByLessor ) ; 
			}
			set
			{
				base.SetValueˡ<decimal?>( _dicˡ, column٠LesseeSurrenderSumPayableByLessor, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string LesseeMakeGoodRequiredIndicator
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠LesseeMakeGoodRequiredIndicator ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠LesseeMakeGoodRequiredIndicator, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string LesseeLeaseNumber
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠LesseeLeaseNumber ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠LesseeLeaseNumber, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public DateTime? LesseeLeaseDate
		{
			get
			{
				return base.GetValueˡ<DateTime?>( _dicˡ, column٠LesseeLeaseDate ) ; 
			}
			set
			{
				base.SetValueˡ<DateTime?>( _dicˡ, column٠LesseeLeaseDate, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string LesseeSendDocsTo
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠LesseeSendDocsTo ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠LesseeSendDocsTo, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string UpdateUserCode
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠UpdateUserCode ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠UpdateUserCode, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public DateTime? UpdateDateTime
		{
			get
			{
				return base.GetValueˡ<DateTime?>( _dicˡ, column٠UpdateDateTime ) ; 
			}
			set
			{
				base.SetValueˡ<DateTime?>( _dicˡ, column٠UpdateDateTime, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public byte[] RowTimestamp
		{
			get
			{
				return base.GetValueˡ<byte[]>( _dicˡ, column٠RowTimestamp ) ; 
			}
			set
			{
				base.SetValueˡ<byte[]>( _dicˡ, column٠RowTimestamp, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string TenantTradingName
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠TenantTradingName ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠TenantTradingName, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string LesseeTradingName
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠LesseeTradingName ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠LesseeTradingName, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string LesseeLiableLegalFeesIndicator
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠LesseeLiableLegalFeesIndicator ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠LesseeLiableLegalFeesIndicator, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public SurrenderDetailGet٠rs1() : base()
		{
			base._dicˡ[ column٠SurrenderDetailID ] = null ;
			base._dicˡ[ column٠TenantSolicitorName ] = null ;
			base._dicˡ[ column٠TenantName ] = null ;
			base._dicˡ[ column٠TenantShopNo ] = null ;
			base._dicˡ[ column٠TenantSurrenderApplicable ] = null ;
			base._dicˡ[ column٠TenantSurrenderDate ] = null ;
			base._dicˡ[ column٠TenantSurrenderSumPayableByLessee ] = null ;
			base._dicˡ[ column٠TenantSurrenderSumPayableByLessor ] = null ;
			base._dicˡ[ column٠TenantMakeGoodRequiredIndicator ] = null ;
			base._dicˡ[ column٠TenantLeaseNumber ] = null ;
			base._dicˡ[ column٠TenantLeaseDate ] = null ;
			base._dicˡ[ column٠TenantSendDocsTo ] = null ;
			base._dicˡ[ column٠LesseeSolicitorName ] = null ;
			base._dicˡ[ column٠LesseeName ] = null ;
			base._dicˡ[ column٠LesseeShopNo ] = null ;
			base._dicˡ[ column٠LesseeSurrenderApplicable ] = null ;
			base._dicˡ[ column٠LesseeSurrenderDate ] = null ;
			base._dicˡ[ column٠LesseeSurrenderSumPayableByLessee ] = null ;
			base._dicˡ[ column٠LesseeSurrenderSumPayableByLessor ] = null ;
			base._dicˡ[ column٠LesseeMakeGoodRequiredIndicator ] = null ;
			base._dicˡ[ column٠LesseeLeaseNumber ] = null ;
			base._dicˡ[ column٠LesseeLeaseDate ] = null ;
			base._dicˡ[ column٠LesseeSendDocsTo ] = null ;
			base._dicˡ[ column٠UpdateUserCode ] = null ;
			base._dicˡ[ column٠UpdateDateTime ] = null ;
			base._dicˡ[ column٠RowTimestamp ] = null ;
			base._dicˡ[ column٠TenantTradingName ] = null ;
			base._dicˡ[ column٠LesseeTradingName ] = null ;
			base._dicˡ[ column٠LesseeLiableLegalFeesIndicator ] = null ;
		 
		}

	}

}

