
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;
using ns = alby.pantheon.codegen;

namespace alby.pantheon.codegen.storedProcedure
{
	public partial class StoredProcedureFactory : acr.StoredProcedureFactoryBase< ns.database.pantheonDatabaseSingletonHelper, ns.database.pantheonDatabase >
	{
		public int SurrenderDetailUpdate
		(
			sds.SqlConnection connˡ, 
			int? SurrenderDetailID, 
			string TenantSolicitorName, 
			string TenantName, 
			string TenantShopNo, 
			string TenantSurrenderApplicable, 
			DateTime? TenantSurrenderDate, 
			decimal? TenantSurrenderSumPayableByLessee, 
			decimal? TenantSurrenderSumPayableByLessor, 
			string TenantMakeGoodRequiredIndicator, 
			string TenantLeaseNumber, 
			DateTime? TenantLeaseDate, 
			string TenantSendDocsTo, 
			string LesseeSolicitorName, 
			string LesseeName, 
			string LesseeShopNo, 
			string LesseeSurrenderApplicable, 
			DateTime? LesseeSurrenderDate, 
			decimal? LesseeSurrenderSumPayableByLessee, 
			decimal? LesseeSurrenderSumPayableByLessor, 
			string LesseeMakeGoodRequiredIndicator, 
			string LesseeLeaseNumber, 
			DateTime? LesseeLeaseDate, 
			string LesseeSendDocsTo, 
			string TenantTradingName, 
			string LesseeTradingName, 
			string LesseeLiableLegalFeesIndicator, 
			string UpdateUserCode, 
			DateTime? UpdateDateTime, 
			ref byte[] RowTimestamp, 
			sds.SqlTransaction tranˡ = null
		)
		{
			const string schemaˡ = "dbo" ; 
			const string spˡ = "SurrenderDetailUpdate" ; 
			 
			scg.List<sds.SqlParameter> parametersˡ = new scg.List<sds.SqlParameter>() ;
			sds.SqlParameter paramˡSurrenderDetailID = base.AddParameterˡ( parametersˡ, "@SurrenderDetailID", SurrenderDetailID, sd.SqlDbType.Int, true, null, 10, 0 ) ; 
			sds.SqlParameter paramˡTenantSolicitorName = base.AddParameterˡ( parametersˡ, "@TenantSolicitorName", TenantSolicitorName, sd.SqlDbType.NVarChar, true, 50, null, null ) ; 
			sds.SqlParameter paramˡTenantName = base.AddParameterˡ( parametersˡ, "@TenantName", TenantName, sd.SqlDbType.NVarChar, true, 200, null, null ) ; 
			sds.SqlParameter paramˡTenantShopNo = base.AddParameterˡ( parametersˡ, "@TenantShopNo", TenantShopNo, sd.SqlDbType.NVarChar, true, 50, null, null ) ; 
			sds.SqlParameter paramˡTenantSurrenderApplicable = base.AddParameterˡ( parametersˡ, "@TenantSurrenderApplicable", TenantSurrenderApplicable, sd.SqlDbType.Char, true, 1, null, null ) ; 
			sds.SqlParameter paramˡTenantSurrenderDate = base.AddParameterˡ( parametersˡ, "@TenantSurrenderDate", TenantSurrenderDate, sd.SqlDbType.DateTime, true, null, null, null ) ; 
			sds.SqlParameter paramˡTenantSurrenderSumPayableByLessee = base.AddParameterˡ( parametersˡ, "@TenantSurrenderSumPayableByLessee", TenantSurrenderSumPayableByLessee, sd.SqlDbType.Decimal, true, null, 28, 10 ) ; 
			sds.SqlParameter paramˡTenantSurrenderSumPayableByLessor = base.AddParameterˡ( parametersˡ, "@TenantSurrenderSumPayableByLessor", TenantSurrenderSumPayableByLessor, sd.SqlDbType.Decimal, true, null, 28, 10 ) ; 
			sds.SqlParameter paramˡTenantMakeGoodRequiredIndicator = base.AddParameterˡ( parametersˡ, "@TenantMakeGoodRequiredIndicator", TenantMakeGoodRequiredIndicator, sd.SqlDbType.Char, true, 1, null, null ) ; 
			sds.SqlParameter paramˡTenantLeaseNumber = base.AddParameterˡ( parametersˡ, "@TenantLeaseNumber", TenantLeaseNumber, sd.SqlDbType.NVarChar, true, 50, null, null ) ; 
			sds.SqlParameter paramˡTenantLeaseDate = base.AddParameterˡ( parametersˡ, "@TenantLeaseDate", TenantLeaseDate, sd.SqlDbType.DateTime, true, null, null, null ) ; 
			sds.SqlParameter paramˡTenantSendDocsTo = base.AddParameterˡ( parametersˡ, "@TenantSendDocsTo", TenantSendDocsTo, sd.SqlDbType.NVarChar, true, 50, null, null ) ; 
			sds.SqlParameter paramˡLesseeSolicitorName = base.AddParameterˡ( parametersˡ, "@LesseeSolicitorName", LesseeSolicitorName, sd.SqlDbType.NVarChar, true, 50, null, null ) ; 
			sds.SqlParameter paramˡLesseeName = base.AddParameterˡ( parametersˡ, "@LesseeName", LesseeName, sd.SqlDbType.NVarChar, true, 200, null, null ) ; 
			sds.SqlParameter paramˡLesseeShopNo = base.AddParameterˡ( parametersˡ, "@LesseeShopNo", LesseeShopNo, sd.SqlDbType.NVarChar, true, 50, null, null ) ; 
			sds.SqlParameter paramˡLesseeSurrenderApplicable = base.AddParameterˡ( parametersˡ, "@LesseeSurrenderApplicable", LesseeSurrenderApplicable, sd.SqlDbType.Char, true, 1, null, null ) ; 
			sds.SqlParameter paramˡLesseeSurrenderDate = base.AddParameterˡ( parametersˡ, "@LesseeSurrenderDate", LesseeSurrenderDate, sd.SqlDbType.DateTime, true, null, null, null ) ; 
			sds.SqlParameter paramˡLesseeSurrenderSumPayableByLessee = base.AddParameterˡ( parametersˡ, "@LesseeSurrenderSumPayableByLessee", LesseeSurrenderSumPayableByLessee, sd.SqlDbType.Decimal, true, null, 28, 10 ) ; 
			sds.SqlParameter paramˡLesseeSurrenderSumPayableByLessor = base.AddParameterˡ( parametersˡ, "@LesseeSurrenderSumPayableByLessor", LesseeSurrenderSumPayableByLessor, sd.SqlDbType.Decimal, true, null, 28, 10 ) ; 
			sds.SqlParameter paramˡLesseeMakeGoodRequiredIndicator = base.AddParameterˡ( parametersˡ, "@LesseeMakeGoodRequiredIndicator", LesseeMakeGoodRequiredIndicator, sd.SqlDbType.Char, true, 1, null, null ) ; 
			sds.SqlParameter paramˡLesseeLeaseNumber = base.AddParameterˡ( parametersˡ, "@LesseeLeaseNumber", LesseeLeaseNumber, sd.SqlDbType.NVarChar, true, 50, null, null ) ; 
			sds.SqlParameter paramˡLesseeLeaseDate = base.AddParameterˡ( parametersˡ, "@LesseeLeaseDate", LesseeLeaseDate, sd.SqlDbType.DateTime, true, null, null, null ) ; 
			sds.SqlParameter paramˡLesseeSendDocsTo = base.AddParameterˡ( parametersˡ, "@LesseeSendDocsTo", LesseeSendDocsTo, sd.SqlDbType.NVarChar, true, 50, null, null ) ; 
			sds.SqlParameter paramˡTenantTradingName = base.AddParameterˡ( parametersˡ, "@TenantTradingName", TenantTradingName, sd.SqlDbType.NVarChar, true, 100, null, null ) ; 
			sds.SqlParameter paramˡLesseeTradingName = base.AddParameterˡ( parametersˡ, "@LesseeTradingName", LesseeTradingName, sd.SqlDbType.NVarChar, true, 100, null, null ) ; 
			sds.SqlParameter paramˡLesseeLiableLegalFeesIndicator = base.AddParameterˡ( parametersˡ, "@LesseeLiableLegalFeesIndicator", LesseeLiableLegalFeesIndicator, sd.SqlDbType.Char, true, 1, null, null ) ; 
			sds.SqlParameter paramˡUpdateUserCode = base.AddParameterˡ( parametersˡ, "@UpdateUserCode", UpdateUserCode, sd.SqlDbType.VarChar, true, 50, null, null ) ; 
			sds.SqlParameter paramˡUpdateDateTime = base.AddParameterˡ( parametersˡ, "@UpdateDateTime", UpdateDateTime, sd.SqlDbType.DateTime, true, null, null, null ) ; 
			sds.SqlParameter paramˡRowTimestamp = base.AddParameterˡ( parametersˡ, "@RowTimestamp", RowTimestamp, sd.SqlDbType.Timestamp, false, null, null, null ) ; 
			sds.SqlParameter paramˡrcˡ = base.AddParameterReturnValueˡ( parametersˡ, "@rcˡ" ) ; 
			 
			sd.DataSet dsˡ = base.Executeˡ( connˡ, tranˡ, schemaˡ, spˡ, parametersˡ ) ;
			 
			RowTimestamp = base.GetParameterValueˡ<byte[]>( paramˡRowTimestamp ) ;
			return base.GetParameterValueˡ<int>( paramˡrcˡ ) ;
		}
	}

}

