
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;
using ns = alby.pantheon.codegen;

namespace alby.pantheon.codegen.table
{
	public partial class AuditingFactory : acr.FactoryBase< Auditing, ns.database.pantheonDatabaseSingletonHelper, ns.database.pantheonDatabase >
	{
		static AuditingFactory() 
		{
			_assemblyˡ = sr.Assembly.GetExecutingAssembly() ;
			_schemaˡ = "dbo" ;
			_tableˡ = "Auditing" ;
			_selectˡ = "select * from {0} t " ;
			_insertˡ = "insert {0} ( [AuditingGUID], [ObjectName], [UserName] ) values ( @AuditingGUID, @ObjectName, @UserName ) " ;
			_insertIdentityˡ = "insert {0} ( [AuditingGUID], [ObjectName], [UserName] ) values ( @AuditingGUID, @ObjectName, @UserName ) " ;
			_updateˡ = "update {0} set [AuditingGUID] = @AuditingGUID, [ObjectName] = @ObjectName, [UserName] = @UserName " ;
			_deleteˡ = "delete {0} " ;
			_whereLoadPKˡ = "" ;
			_whereSavePKˡ = "" ;
		}

		public scg.List<Auditing> Loadˡ
		(
			sds.SqlConnection connˡ,
			int? topNˡ = null,
			scg.List<acr.CodeGenOrderBy> orderByˡ = null,
			sds.SqlTransaction tranˡ = null
		)
		{
			scg.List<sds.SqlParameter> parametersˡ = new scg.List<sds.SqlParameter>();
			string whereˡ = "";
			string sqlˡ = "" ; 
			return base.ExecuteQueryˡ( connˡ, tranˡ, parametersˡ, _assemblyˡ, _selectˡ, false, whereˡ, false, topNˡ, orderByˡ, out sqlˡ ) ;
		}

		public scg.List<Auditing> LoadByWhereˡ
		(
			sds.SqlConnection connˡ,
			string whereˡ,
			scg.List<sds.SqlParameter> parametersˡ = null,
			int? topNˡ = null,
			scg.List<acr.CodeGenOrderBy> orderByˡ = null,
			sds.SqlTransaction tranˡ = null
		)
		{
			string sqlˡ = "" ; 
			return base.ExecuteQueryˡ( connˡ, tranˡ, parametersˡ, _assemblyˡ, _selectˡ, false, whereˡ, false, topNˡ, orderByˡ, out sqlˡ ) ;
		}

	}

}

