
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

namespace alby.pantheon.codegen.table
{
	public partial class Chain : acr.RowBase
	{
		public const string column٠ChainID  = "ChainID" ;
		public const string column٠ChainCode  = "ChainCode" ;
		public const string column٠ChainDescription  = "ChainDescription" ;
		public const string column٠UpdateUserCode  = "UpdateUserCode" ;
		public const string column٠UpdateDateTime  = "UpdateDateTime" ;
		public const string column٠RowTimestamp  = "RowTimestamp" ;
		public const string column٠DeletionIndicator  = "DeletionIndicator" ;
		 
		public int? ChainID
		{
			get
			{
				return base.GetValueˡ<int?>( _dicˡ, column٠ChainID ) ; 
			}
			set
			{
				base.SetValueˡ<int?>( _dicˡ, column٠ChainID, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string ChainCode
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠ChainCode ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠ChainCode, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string ChainDescription
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠ChainDescription ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠ChainDescription, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string UpdateUserCode
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠UpdateUserCode ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠UpdateUserCode, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public DateTime? UpdateDateTime
		{
			get
			{
				return base.GetValueˡ<DateTime?>( _dicˡ, column٠UpdateDateTime ) ; 
			}
			set
			{
				base.SetValueˡ<DateTime?>( _dicˡ, column٠UpdateDateTime, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public byte[] RowTimestamp
		{
			get
			{
				return base.GetValueˡ<byte[]>( _dicˡ, column٠RowTimestamp ) ; 
			}
			set
			{
				base.SetValueˡ<byte[]>( _dicˡ, column٠RowTimestamp, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string DeletionIndicator
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠DeletionIndicator ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠DeletionIndicator, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public Chain() : base()
		{
			base._dicˡ[ column٠ChainID ] = null ;
			base._dicˡ[ column٠ChainCode ] = null ;
			base._dicˡ[ column٠ChainDescription ] = null ;
			base._dicˡ[ column٠UpdateUserCode ] = null ;
			base._dicˡ[ column٠UpdateDateTime ] = null ;
			base._dicˡ[ column٠RowTimestamp ] = null ;
			base._dicˡ[ column٠DeletionIndicator ] = null ;
		 
			base._dicPKˡ[ column٠ChainID ] = null ;
		 
		}

	}

}

