
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

namespace alby.pantheon.codegen.table
{
	public partial class CostCentreStage : acr.RowBase
	{
		public Centre parent٠Centre٠By٠CentreID( sds.SqlConnection connˡ, sds.SqlTransaction tranˡ = null )
		{
			CentreFactory factoryˡ = new CentreFactory() ; 
			return factoryˡ.LoadByPrimaryKeyˡ
			(
				connˡ,
				this.CentreID, 
				tranˡ
			) ;
		}

		public scg.List<CostCentreOutgoing> children٠CostCentreOutgoing٠By٠CostCentreStageID( sds.SqlConnection connˡ, int? topNˡ = null, scg.List<acr.CodeGenOrderBy> orderByˡ = null, sds.SqlTransaction tranˡ = null )
		{
			CostCentreOutgoingFactory factoryˡ = new CostCentreOutgoingFactory() ; 
			return factoryˡ.LoadByForeignKey٠From٠CostCentreStage٠By٠CostCentreStageID
			(
				connˡ,
				this.CostCentreStageID, 
				topNˡ,
				orderByˡ,
				tranˡ
			) ;
		}

		public scg.List<CostCentreOutgoingArchive> children٠CostCentreOutgoingArchive٠By٠CostCentreStageID( sds.SqlConnection connˡ, int? topNˡ = null, scg.List<acr.CodeGenOrderBy> orderByˡ = null, sds.SqlTransaction tranˡ = null )
		{
			CostCentreOutgoingArchiveFactory factoryˡ = new CostCentreOutgoingArchiveFactory() ; 
			return factoryˡ.LoadByForeignKey٠From٠CostCentreStage٠By٠CostCentreStageID
			(
				connˡ,
				this.CostCentreStageID, 
				topNˡ,
				orderByˡ,
				tranˡ
			) ;
		}

		public scg.List<Lease> children٠Lease٠By٠CostCentreStageID( sds.SqlConnection connˡ, int? topNˡ = null, scg.List<acr.CodeGenOrderBy> orderByˡ = null, sds.SqlTransaction tranˡ = null )
		{
			LeaseFactory factoryˡ = new LeaseFactory() ; 
			return factoryˡ.LoadByForeignKey٠From٠CostCentreStage٠By٠CostCentreStageID
			(
				connˡ,
				this.CostCentreStageID, 
				topNˡ,
				orderByˡ,
				tranˡ
			) ;
		}

	}

}

