
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

namespace alby.pantheon.codegen.table
{
	public partial class Document : acr.RowBase
	{
		public const string column٠DocumentID  = "DocumentID" ;
		public const string column٠LeaseID  = "LeaseID" ;
		public const string column٠Description  = "Description" ;
		public const string column٠Type  = "Type" ;
		public const string column٠BinaryData  = "BinaryData" ;
		public const string column٠UpdateUserCode  = "UpdateUserCode" ;
		public const string column٠UpdateDateTime  = "UpdateDateTime" ;
		public const string column٠RowTimestamp  = "RowTimestamp" ;
		 
		public int? DocumentID
		{
			get
			{
				return base.GetValueˡ<int?>( _dicˡ, column٠DocumentID ) ; 
			}
			set
			{
				base.SetValueˡ<int?>( _dicˡ, column٠DocumentID, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public int? LeaseID
		{
			get
			{
				return base.GetValueˡ<int?>( _dicˡ, column٠LeaseID ) ; 
			}
			set
			{
				base.SetValueˡ<int?>( _dicˡ, column٠LeaseID, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string Description
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠Description ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠Description, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string Type
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠Type ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠Type, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public byte[] BinaryData
		{
			get
			{
				return base.GetValueˡ<byte[]>( _dicˡ, column٠BinaryData ) ; 
			}
			set
			{
				base.SetValueˡ<byte[]>( _dicˡ, column٠BinaryData, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string UpdateUserCode
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠UpdateUserCode ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠UpdateUserCode, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public DateTime? UpdateDateTime
		{
			get
			{
				return base.GetValueˡ<DateTime?>( _dicˡ, column٠UpdateDateTime ) ; 
			}
			set
			{
				base.SetValueˡ<DateTime?>( _dicˡ, column٠UpdateDateTime, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public byte[] RowTimestamp
		{
			get
			{
				return base.GetValueˡ<byte[]>( _dicˡ, column٠RowTimestamp ) ; 
			}
			set
			{
				base.SetValueˡ<byte[]>( _dicˡ, column٠RowTimestamp, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public Document() : base()
		{
			base._dicˡ[ column٠DocumentID ] = null ;
			base._dicˡ[ column٠LeaseID ] = null ;
			base._dicˡ[ column٠Description ] = null ;
			base._dicˡ[ column٠Type ] = null ;
			base._dicˡ[ column٠BinaryData ] = null ;
			base._dicˡ[ column٠UpdateUserCode ] = null ;
			base._dicˡ[ column٠UpdateDateTime ] = null ;
			base._dicˡ[ column٠RowTimestamp ] = null ;
		 
			base._dicPKˡ[ column٠DocumentID ] = null ;
		 
		}

	}

}

