
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;
using ns = alby.pantheon.codegen;

namespace alby.pantheon.codegen.table
{
	public partial class dtpropertiesFactory : acr.FactoryBase< dtproperties, ns.database.pantheonDatabaseSingletonHelper, ns.database.pantheonDatabase >
	{
		static dtpropertiesFactory() 
		{
			_assemblyˡ = sr.Assembly.GetExecutingAssembly() ;
			_schemaˡ = "dbo" ;
			_tableˡ = "dtproperties" ;
			_selectˡ = "select * from {0} t " ;
			_insertˡ = "insert {0} ( [objectid], [property], [value], [uvalue], [lvalue], [version] ) values ( @objectid, @property, @value, @uvalue, @lvalue, @version ) " ;
			_insertIdentityˡ = "insert {0} ( [id], [objectid], [property], [value], [uvalue], [lvalue], [version] ) values ( @id, @objectid, @property, @value, @uvalue, @lvalue, @version ) " ;
			_updateˡ = "update {0} set [objectid] = @objectid, [property] = @property, [value] = @value, [uvalue] = @uvalue, [lvalue] = @lvalue, [version] = @version " ;
			_deleteˡ = "delete {0} " ;
			_whereLoadPKˡ = "where [id] = @pk_id and [property] = @pk_property " ;
			_whereSavePKˡ = "where [id] = @pk_id and [property] = @pk_property " ;
		}

		public dtproperties Saveˡ( sds.SqlConnection connˡ, dtproperties rowˡ, acr.CodeGenSaveStrategy saveStrategyˡ = acr.CodeGenSaveStrategy.Normal, bool identityProvidedˡ = false, sds.SqlTransaction tranˡ = null )
		{
			scg.List<sds.SqlParameter> parametersˡ = new scg.List<sds.SqlParameter>();
			base.AddParameterˡ( parametersˡ, "@pk_id", rowˡ.PrimaryKeyDictionaryˡ[ dtproperties.column٠id ] );
			base.AddParameterˡ( parametersˡ, "@pk_property", rowˡ.PrimaryKeyDictionaryˡ[ dtproperties.column٠property ] );
			base.AddParameterˡ( parametersˡ, "@id", rowˡ.id, sd.SqlDbType.Int );
			base.AddParameterˡ( parametersˡ, "@objectid", rowˡ.objectid, sd.SqlDbType.Int );
			base.AddParameterˡ( parametersˡ, "@property", rowˡ.property, sd.SqlDbType.NText );
			base.AddParameterˡ( parametersˡ, "@value", rowˡ.value, sd.SqlDbType.NText );
			base.AddParameterˡ( parametersˡ, "@uvalue", rowˡ.uvalue, sd.SqlDbType.NText );
			base.AddParameterˡ( parametersˡ, "@lvalue", rowˡ.lvalue, sd.SqlDbType.Image );
			base.AddParameterˡ( parametersˡ, "@version", rowˡ.version, sd.SqlDbType.Int );

			int? identityIDˡ = null ;
			object objˡ = null ;
		 
			acr.SaveEnum saveResultˡ ;
		 
			if ( saveStrategyˡ != acr.CodeGenSaveStrategy.Normal )
			{
				saveResultˡ = base.ExecuteForceSaveˡ( rowˡ, connˡ, tranˡ, parametersˡ, saveStrategyˡ, _insertˡ, _insertIdentityˡ, _updateˡ, _deleteˡ, _whereLoadPKˡ, true, identityProvidedˡ, out objˡ ) ;
				if ( objˡ != null )
					identityIDˡ = int.Parse( objˡ.ToString() ) ;
			}
			else
			{
				saveResultˡ = base.ExecuteSaveˡ( rowˡ, connˡ, tranˡ, parametersˡ, _insertˡ, _insertIdentityˡ, _updateˡ, _deleteˡ, _whereSavePKˡ, true, identityProvidedˡ, out objˡ ) ;
				if ( objˡ != null )
					identityIDˡ = int.Parse( objˡ.ToString() ) ;
			}
		 
			if ( saveResultˡ == acr.SaveEnum.Update ) 
				return this.LoadByPrimaryKeyˡ( connˡ, rowˡ.id, rowˡ.property, tranˡ ) ;
			else
			if ( saveResultˡ == acr.SaveEnum.Insert ) 
				return this.LoadByPrimaryKeyˡ( connˡ, identityIDˡ, rowˡ.property, tranˡ ) ;
			else
			if ( saveResultˡ == acr.SaveEnum.Delete )
				return null ;
			else
				return rowˡ ;
		}

		public scg.List<dtproperties> Saveˡ( sds.SqlConnection connˡ, scg.List<dtproperties> rowListˡ, acr.CodeGenSaveStrategy saveStrategyˡ = acr.CodeGenSaveStrategy.Normal,  bool identityProvidedˡ = false, sds.SqlTransaction tranˡ = null )
		{
			scg.List<dtproperties> rowList2ˡ = new scg.List<dtproperties>();
			foreach( dtproperties rowˡ in rowListˡ )
			{
				dtproperties row2ˡ = this.Saveˡ( connˡ, rowˡ, saveStrategyˡ, identityProvidedˡ, tranˡ ) ;
				if ( row2ˡ != null )	rowList2ˡ.Add( row2ˡ ) ;
			}
			return rowList2ˡ ;
		}

		public dtproperties LoadByPrimaryKeyˡ
		(
			sds.SqlConnection connˡ,
			int? id,
			string property,
			sds.SqlTransaction tranˡ = null
		)
		{
			scg.List<sds.SqlParameter> parametersˡ = new scg.List<sds.SqlParameter>();
			base.AddParameterˡ( parametersˡ, "@pk_id", id );
			base.AddParameterˡ( parametersˡ, "@pk_property", property );
			return base.ExecuteQueryReturnOneˡ( connˡ, tranˡ, parametersˡ, _assemblyˡ, _selectˡ, false, _whereLoadPKˡ, false ) ;
		}

		public scg.List<dtproperties> Loadˡ
		(
			sds.SqlConnection connˡ,
			int? topNˡ = null,
			scg.List<acr.CodeGenOrderBy> orderByˡ = null,
			sds.SqlTransaction tranˡ = null
		)
		{
			scg.List<sds.SqlParameter> parametersˡ = new scg.List<sds.SqlParameter>();
			string whereˡ = "";
			string sqlˡ = "" ; 
			return base.ExecuteQueryˡ( connˡ, tranˡ, parametersˡ, _assemblyˡ, _selectˡ, false, whereˡ, false, topNˡ, orderByˡ, out sqlˡ ) ;
		}

		public scg.List<dtproperties> LoadByWhereˡ
		(
			sds.SqlConnection connˡ,
			string whereˡ,
			scg.List<sds.SqlParameter> parametersˡ = null,
			int? topNˡ = null,
			scg.List<acr.CodeGenOrderBy> orderByˡ = null,
			sds.SqlTransaction tranˡ = null
		)
		{
			string sqlˡ = "" ; 
			return base.ExecuteQueryˡ( connˡ, tranˡ, parametersˡ, _assemblyˡ, _selectˡ, false, whereˡ, false, topNˡ, orderByˡ, out sqlˡ ) ;
		}

	}

}

