
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

namespace alby.pantheon.codegen.table
{
	public partial class LeaseGuarantor : acr.RowBase
	{
		public Lease parent٠Lease٠By٠LeaseID( sds.SqlConnection connˡ, sds.SqlTransaction tranˡ = null )
		{
			LeaseFactory factoryˡ = new LeaseFactory() ; 
			return factoryˡ.LoadByPrimaryKeyˡ
			(
				connˡ,
				this.LeaseID, 
				tranˡ
			) ;
		}

		public Party parent٠Party٠By٠PartyID( sds.SqlConnection connˡ, sds.SqlTransaction tranˡ = null )
		{
			PartyFactory factoryˡ = new PartyFactory() ; 
			return factoryˡ.LoadByPrimaryKeyˡ
			(
				connˡ,
				this.PartyID, 
				tranˡ
			) ;
		}

	}

}

