
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

namespace alby.pantheon.codegen.table
{
	public partial class Party : acr.RowBase
	{
		public scg.List<Address> children٠Address٠By٠PartyID( sds.SqlConnection connˡ, int? topNˡ = null, scg.List<acr.CodeGenOrderBy> orderByˡ = null, sds.SqlTransaction tranˡ = null )
		{
			AddressFactory factoryˡ = new AddressFactory() ; 
			return factoryˡ.LoadByForeignKey٠From٠Party٠By٠PartyID
			(
				connˡ,
				this.PartyID, 
				topNˡ,
				orderByˡ,
				tranˡ
			) ;
		}

		public scg.List<Centre> children٠Centre٠By٠PartyID( sds.SqlConnection connˡ, int? topNˡ = null, scg.List<acr.CodeGenOrderBy> orderByˡ = null, sds.SqlTransaction tranˡ = null )
		{
			CentreFactory factoryˡ = new CentreFactory() ; 
			return factoryˡ.LoadByForeignKey٠From٠Party٠By٠PartyID
			(
				connˡ,
				this.PartyID, 
				topNˡ,
				orderByˡ,
				tranˡ
			) ;
		}

		public scg.List<Communication> children٠Communication٠By٠PartyID( sds.SqlConnection connˡ, int? topNˡ = null, scg.List<acr.CodeGenOrderBy> orderByˡ = null, sds.SqlTransaction tranˡ = null )
		{
			CommunicationFactory factoryˡ = new CommunicationFactory() ; 
			return factoryˡ.LoadByForeignKey٠From٠Party٠By٠PartyID
			(
				connˡ,
				this.PartyID, 
				topNˡ,
				orderByˡ,
				tranˡ
			) ;
		}

		public scg.List<Franchise> children٠Franchise٠By٠PartyID( sds.SqlConnection connˡ, int? topNˡ = null, scg.List<acr.CodeGenOrderBy> orderByˡ = null, sds.SqlTransaction tranˡ = null )
		{
			FranchiseFactory factoryˡ = new FranchiseFactory() ; 
			return factoryˡ.LoadByForeignKey٠From٠Party٠By٠PartyID
			(
				connˡ,
				this.PartyID, 
				topNˡ,
				orderByˡ,
				tranˡ
			) ;
		}

		public scg.List<LeaseExecutive> children٠LeaseExecutive٠By٠PartyID( sds.SqlConnection connˡ, int? topNˡ = null, scg.List<acr.CodeGenOrderBy> orderByˡ = null, sds.SqlTransaction tranˡ = null )
		{
			LeaseExecutiveFactory factoryˡ = new LeaseExecutiveFactory() ; 
			return factoryˡ.LoadByForeignKey٠From٠Party٠By٠PartyID
			(
				connˡ,
				this.PartyID, 
				topNˡ,
				orderByˡ,
				tranˡ
			) ;
		}

		public scg.List<LeaseGuarantor> children٠LeaseGuarantor٠By٠PartyID( sds.SqlConnection connˡ, int? topNˡ = null, scg.List<acr.CodeGenOrderBy> orderByˡ = null, sds.SqlTransaction tranˡ = null )
		{
			LeaseGuarantorFactory factoryˡ = new LeaseGuarantorFactory() ; 
			return factoryˡ.LoadByForeignKey٠From٠Party٠By٠PartyID
			(
				connˡ,
				this.PartyID, 
				topNˡ,
				orderByˡ,
				tranˡ
			) ;
		}

		public scg.List<Lessee> children٠Lessee٠By٠PartyID( sds.SqlConnection connˡ, int? topNˡ = null, scg.List<acr.CodeGenOrderBy> orderByˡ = null, sds.SqlTransaction tranˡ = null )
		{
			LesseeFactory factoryˡ = new LesseeFactory() ; 
			return factoryˡ.LoadByForeignKey٠From٠Party٠By٠PartyID
			(
				connˡ,
				this.PartyID, 
				topNˡ,
				orderByˡ,
				tranˡ
			) ;
		}

		public scg.List<Solicitor> children٠Solicitor٠By٠PartyID( sds.SqlConnection connˡ, int? topNˡ = null, scg.List<acr.CodeGenOrderBy> orderByˡ = null, sds.SqlTransaction tranˡ = null )
		{
			SolicitorFactory factoryˡ = new SolicitorFactory() ; 
			return factoryˡ.LoadByForeignKey٠From٠Party٠By٠PartyID
			(
				connˡ,
				this.PartyID, 
				topNˡ,
				orderByˡ,
				tranˡ
			) ;
		}

		public scg.List<Staff> children٠Staff٠By٠PartyID( sds.SqlConnection connˡ, int? topNˡ = null, scg.List<acr.CodeGenOrderBy> orderByˡ = null, sds.SqlTransaction tranˡ = null )
		{
			StaffFactory factoryˡ = new StaffFactory() ; 
			return factoryˡ.LoadByForeignKey٠From٠Party٠By٠PartyID
			(
				connˡ,
				this.PartyID, 
				topNˡ,
				orderByˡ,
				tranˡ
			) ;
		}

	}

}

