
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

namespace alby.pantheon.codegen.table
{
	public partial class RentReview : acr.RowBase
	{
		public RentReviewType parent٠RentReviewType٠By٠RentReviewTypeID( sds.SqlConnection connˡ, sds.SqlTransaction tranˡ = null )
		{
			RentReviewTypeFactory factoryˡ = new RentReviewTypeFactory() ; 
			return factoryˡ.LoadByPrimaryKeyˡ
			(
				connˡ,
				this.RentReviewTypeID, 
				tranˡ
			) ;
		}

		public scg.List<ConsumerPriceIndexRentReview> children٠ConsumerPriceIndexRentReview٠By٠RentReviewID( sds.SqlConnection connˡ, int? topNˡ = null, scg.List<acr.CodeGenOrderBy> orderByˡ = null, sds.SqlTransaction tranˡ = null )
		{
			ConsumerPriceIndexRentReviewFactory factoryˡ = new ConsumerPriceIndexRentReviewFactory() ; 
			return factoryˡ.LoadByForeignKey٠From٠RentReview٠By٠RentReviewID
			(
				connˡ,
				this.RentReviewID, 
				topNˡ,
				orderByˡ,
				tranˡ
			) ;
		}

		public scg.List<FixedIncreaseRentReview> children٠FixedIncreaseRentReview٠By٠RentReviewID( sds.SqlConnection connˡ, int? topNˡ = null, scg.List<acr.CodeGenOrderBy> orderByˡ = null, sds.SqlTransaction tranˡ = null )
		{
			FixedIncreaseRentReviewFactory factoryˡ = new FixedIncreaseRentReviewFactory() ; 
			return factoryˡ.LoadByForeignKey٠From٠RentReview٠By٠RentReviewID
			(
				connˡ,
				this.RentReviewID, 
				topNˡ,
				orderByˡ,
				tranˡ
			) ;
		}

		public scg.List<RentDetail> children٠RentDetail٠By٠RentReviewID( sds.SqlConnection connˡ, int? topNˡ = null, scg.List<acr.CodeGenOrderBy> orderByˡ = null, sds.SqlTransaction tranˡ = null )
		{
			RentDetailFactory factoryˡ = new RentDetailFactory() ; 
			return factoryˡ.LoadByForeignKey٠From٠RentReview٠By٠RentReviewID
			(
				connˡ,
				this.RentReviewID, 
				topNˡ,
				orderByˡ,
				tranˡ
			) ;
		}

	}

}

