
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

namespace alby.pantheon.codegen.table
{
	public partial class SolicitorWebService : acr.RowBase
	{
		public const string column٠SolicitorWebServiceGUID  = "SolicitorWebServiceGUID" ;
		public const string column٠Name  = "Name" ;
		public const string column٠DevUrl  = "DevUrl" ;
		public const string column٠IntgUrl  = "IntgUrl" ;
		public const string column٠TestUrl  = "TestUrl" ;
		public const string column٠StagUrl  = "StagUrl" ;
		public const string column٠ProdUrl  = "ProdUrl" ;
		public const string column٠DRUrl  = "DRUrl" ;
		public const string column٠DevCertFilename  = "DevCertFilename" ;
		public const string column٠IntgCertFilename  = "IntgCertFilename" ;
		public const string column٠TestCertFilename  = "TestCertFilename" ;
		public const string column٠StagCertFilename  = "StagCertFilename" ;
		public const string column٠ProdCertFilename  = "ProdCertFilename" ;
		public const string column٠DRCertFilename  = "DRCertFilename" ;
		public const string column٠UpdateUserCode  = "UpdateUserCode" ;
		public const string column٠UpdateDateTime  = "UpdateDateTime" ;
		public const string column٠RowTimestamp  = "RowTimestamp" ;
		 
		public Guid? SolicitorWebServiceGUID
		{
			get
			{
				return base.GetValueˡ<Guid?>( _dicˡ, column٠SolicitorWebServiceGUID ) ; 
			}
			set
			{
				base.SetValueˡ<Guid?>( _dicˡ, column٠SolicitorWebServiceGUID, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string Name
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠Name ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠Name, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string DevUrl
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠DevUrl ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠DevUrl, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string IntgUrl
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠IntgUrl ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠IntgUrl, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string TestUrl
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠TestUrl ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠TestUrl, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string StagUrl
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠StagUrl ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠StagUrl, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string ProdUrl
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠ProdUrl ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠ProdUrl, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string DRUrl
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠DRUrl ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠DRUrl, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string DevCertFilename
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠DevCertFilename ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠DevCertFilename, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string IntgCertFilename
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠IntgCertFilename ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠IntgCertFilename, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string TestCertFilename
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠TestCertFilename ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠TestCertFilename, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string StagCertFilename
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠StagCertFilename ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠StagCertFilename, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string ProdCertFilename
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠ProdCertFilename ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠ProdCertFilename, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string DRCertFilename
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠DRCertFilename ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠DRCertFilename, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string UpdateUserCode
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠UpdateUserCode ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠UpdateUserCode, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public DateTime? UpdateDateTime
		{
			get
			{
				return base.GetValueˡ<DateTime?>( _dicˡ, column٠UpdateDateTime ) ; 
			}
			set
			{
				base.SetValueˡ<DateTime?>( _dicˡ, column٠UpdateDateTime, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public byte[] RowTimestamp
		{
			get
			{
				return base.GetValueˡ<byte[]>( _dicˡ, column٠RowTimestamp ) ; 
			}
			set
			{
				base.SetValueˡ<byte[]>( _dicˡ, column٠RowTimestamp, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public SolicitorWebService() : base()
		{
			base._dicˡ[ column٠SolicitorWebServiceGUID ] = null ;
			base._dicˡ[ column٠Name ] = null ;
			base._dicˡ[ column٠DevUrl ] = null ;
			base._dicˡ[ column٠IntgUrl ] = null ;
			base._dicˡ[ column٠TestUrl ] = null ;
			base._dicˡ[ column٠StagUrl ] = null ;
			base._dicˡ[ column٠ProdUrl ] = null ;
			base._dicˡ[ column٠DRUrl ] = null ;
			base._dicˡ[ column٠DevCertFilename ] = null ;
			base._dicˡ[ column٠IntgCertFilename ] = null ;
			base._dicˡ[ column٠TestCertFilename ] = null ;
			base._dicˡ[ column٠StagCertFilename ] = null ;
			base._dicˡ[ column٠ProdCertFilename ] = null ;
			base._dicˡ[ column٠DRCertFilename ] = null ;
			base._dicˡ[ column٠UpdateUserCode ] = null ;
			base._dicˡ[ column٠UpdateDateTime ] = null ;
			base._dicˡ[ column٠RowTimestamp ] = null ;
		 
			base._dicPKˡ[ column٠SolicitorWebServiceGUID ] = null ;
		 
		}

	}

}

