
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

namespace alby.pantheon.codegen.table
{
	public partial class SolicitorWebService : acr.RowBase
	{
		public scg.List<Centre> children٠Centre٠By٠SolicitorWebServiceGUID( sds.SqlConnection connˡ, int? topNˡ = null, scg.List<acr.CodeGenOrderBy> orderByˡ = null, sds.SqlTransaction tranˡ = null )
		{
			CentreFactory factoryˡ = new CentreFactory() ; 
			return factoryˡ.LoadByForeignKey٠From٠SolicitorWebService٠By٠SolicitorWebServiceGUID
			(
				connˡ,
				this.SolicitorWebServiceGUID, 
				topNˡ,
				orderByˡ,
				tranˡ
			) ;
		}

	}

}

